- pages/Getting Started/Installation.md
I've packaged Hyprland for openSUSE: https://build.opensuse.org/package/show/X11:Wayland/hyprland,  
these are the instructions to install it (or build from source).
The package currently patches Hyprland twice, @vaxerski you might consider merging them?
- it drops the deprecated `gethostbyname("localhost")` call in `hyprctl/main.cpp`, as binaries calling this should not be part of openSUSE (should use getaddrinfo instead); but in this case the call seems to be leftover from a previous iteration anyways and of little use. [gethostbyname.patch](https://opi-proxy.opensuse.org/?obs_api_link=https%3A%2F%2Fapi.opensuse.org%2Fsource%2FX11%3AWayland%2Fhyprland%2Fgethostbyname.patch&obs_instance=openSUSE)
- it patches the <compiler>.get_version() to <compiler>.version() in `meson.build`, as the …
> Added openSUSE Tumbleweed instructions to Installation

- pages/Configuring/Variables.md
The documentation states it's in milliseconds, but in practice it's currently interpreted as Hz.
> Correct unit for input:repeat_rate

- pages/Configuring/Dwindle-Layout.md
preserve_split has to be enabled for togglesplit to do anything. This makes sense, but it isn't clear from the documentation.
> Make togglesplit requirements clear

- pages/Getting Started/Installation.md
I just did a fresh arch install and Hyprland wouldn't build without installing `libxkbcommon`, `xcb-util-wm`, and `xorg-xwayland` in addition to the dependencies already on the wiki. This PR adds these to the list of dependencies so people in the future don't have to go searching for what's missing.
Also updates the text just below the list of dependencies, as requested on the discord server.
> Add necessary dependencies for building on Arch

- pages/Getting Started/Installation.md
adding ``emaint sync -r wayland-desktop`` will help prevent non-existent directory errors when trying to install hyprland on gentoo.
> Help prevent errors

- pages/Getting Started/Installation.md
Changed wrong file names in the release install guide to match the ones in the actual release tarball.
> Changed Wrong File Name

- pages/Configuring/Environment-variables.md
it seemed to link to Configuration/FAQ, which of course gave a 404, so it's just a small fix for that
> fix link to faq on configuration/envars page

- pages/Configuring/Window-Rules.md
Simply saying "`RULE` is a rule" isn't very helpful imo
> clarify window rule description: link to "Rules" section

- pages/Useful Utilities/Status-Bars.md
Adds information how to archive blur on HybridBar using hyprland. I hope I did use the right terms in the change.
This PR depends on https://github.com/vars1ty/HybridBar/pull/27 to be merged to allow setting the layer namespace, else the part about being able to change the namespace name should be removed.
> Add information about blurring HybridBar

- pages/Useful Utilities/App-Launchers.md
Fuzzel is an application launcher for wlroots based Wayland compositors, similar to rofi's drun mode. It's source code is on [Codeberg](https://codeberg.org/dnkl/fuzzel)
> add a recomended launcher: fuzzel

- pages/Configuring/Dispatchers.md
This pull requests describes the `exact` option for `splitratio` introduced in [#1245](https://github.com/hyprwm/Hyprland/pull/1245).
> Mention 'exact' option for splitratio

- pages/Configuring/Using-hyprctl.md
doesn't use the prefix "kb_" for "layout" which results in an error.
> fix layout instead of kb_layout

- pages/Useful Utilities/Hyprland-desktop-portal.md
I could add more details to  it though actually to install the dependencies on gentoo you need to do these modifications respectively
```
=dev-qt/qtbase-6.4.0
=dev-qt/qtwayland-6.4.0
=dev-qt/qtdeclarative-6.4.0
=dev-qt/qtshadertools-6.4.0
```
```
dev-qt/qtbase opengl X
dev-qt/qtdeclarative opengl
gui-libs/xdg-desktop-portal-hyprland select-window select-region
sys-apps/xdg-desktop-portal screencast
```
```
#XDPH
gui-libs/xdg-desktop-portal-hyprland **
=dev-qt/qtbase-6.4.0
=dev-qt/qtwayland-6.4.0
=dev-qt/qtdeclarative-6.4.0
=dev-qt/qtshadertools-6.4.0
```
Instead of X on qtbase you could also use egl and eglfs
> add gentoo overlay for xdg-desktop-portal-hyprland

- pages/FAQ/_index.md
Updated the faq entry regarding multi-gpu with Nvidia to reflect the recent fix in 525.60.11
> Updated Nvidia entry with multi-gpu fix

- pages/Configuring/Binds.md
- pages/Configuring/Environment-variables.md
- pages/Getting Started/Master-Tutorial.md
- pages/Useful Utilities/App-Clients.md
Some moron thought the wording on the wiki was not clear enough.
This hopefully brings the level of """complicated""" sentences to their elementary English level and make it more readable by the general Linux community.
Also closes #85, #92 and #96
> clarify wording and fix broken links

- pages/Getting Started/Installation.md
I had to do `yay -S meson` before I could run `sudo make install` without error.
(Arch Linux, VMWare)
> Missing Dep?

- pages/Configuring/Binds.md
Hey, I found that the link to list of dispatchers in the [Global Keybinds](http://wiki.hyprland.org/Configuring/Binds/#global-keybinds) section of the [Binds](https://wiki.hyprland.org/Configuring/Binds/#global-keybinds) page is currently broken. I have fixed the link with the correct one.
> Fix broken link to list of dispatchers

- pages/Useful Utilities/Other.md
Change hyprland-per-window-layout to [another](https://github.com/coffebar/hyprland-per-window-layout) version: with zero configuration, multi-keyboard support and available  to install from package manager
> update Other.md: Change hyprland-per-window-layout to better fork

- pages/Configuring/Master-Layout.md
Adds relevant documentation for the feature added in https://github.com/hyprwm/Hyprland/pull/1522
I renamed the 'params' for the `layoutmsg` dispatcher to command, let me know if that should be called differently (as having param and params is kinda ambiguous).
> Added documentation for the new layoutmsg params feature

- pages/Configuring/Variables.md
I don't see any reason to say "self-explanatory" instead of providing a description.
> update "self-explanatory" descriptions

- pages/FAQ/_index.md
VRR can cause flickering on some monitors in desktop scenarios. Add a recommendation to change VRR to `2` if this is happening.
> Add FAQ about VRR flickering

- pages/FAQ/_index.md
`wl-paste -p --watch wl-copy -pc`.
I haven't tested the new solution for *that* long yet, but I'm fairly confident that it works, at least better than the original solution which was already flawed.
> new solution to disable middle-click paste

- pages/Useful Utilities/Clipboard-Managers.md
In the clipboard manager section for clipman you state `for rofi users` bust instead of showing an example with `rofi` you used `wofi
> Replaced wofi with rofi

- pages/Getting Started/Installation.md
libdisplay-info (from the AUR) is required for wlroots drm backend, which Hyprland depends on. Failure to install this package results in linking errors at compile time. libliftoff is not a hard requirement (meaning it builds fine without it), but seems useful to include.
I don't know enough about the other distros to include their version of the packages to the list.
> Add libliftoff and libdisplay-info

- pages/Useful Utilities/Status-Bars.md
I've noticed the listeners do not update while their values are only present in the class attribute, so either the scripts would have to be merged to one output or one can use a hidden element like this to keep the variables updated. For further context see [this issue on eww](https://github.com/elkowar/eww/issues/669)
> Fix for eww listeners not updating properly

- pages/FAQ/_index.md
I was having trouble with getting the cursor to work on chromium/electron flatpak applications. I updated this section of the documentation with what worked for me.
> Update mouse cursor documentation

- pages/Useful Utilities/Clipboard-Managers.md
I've noticed that a dispatcher keyword is missing in the clipman manual.
> Missing 'exec' keyword added to the clipman manual.

- pages/Configuring/Using-hyprctl.md
I spent a bit longer than I should have figuring out that for hyprland, just the device name alone is enough, whereas on sway you would need `input:keyboard` or `input:DEVICE_NAME`. Also wanted to share a tip for anyone who uses several layouts with different variants or global options on each.
> Update switchxkblayout section

- pages/Configuring/Binds.md
wpctl seems to increase the volume without any limit by default, which *might* damage  earphones or make ears hurty, -l 1.5 option limits this to sane levels.
> Add volume limit to keybinds

- pages/Configuring/Variables.md
Changed default values for "animate_manual_resizes" and "animate_mouse_windowdragging" to _false_ following [this commit](https://github.com/hyprwm/Hyprland/commit/41f7736c8521162cb3ea5f3c003e0643c1bcf616).
> "animate_manual_resizes" default to false

- pages/Configuring/Variables.md
- pages/Configuring/Window-Rules.md
Did some minor changes to the wiki - 
1) Added wikipedia link to the window rule regex topic so that people who are not well versed with programming can understand what are regexes. Wikipedia explained regex in a simple and lucid english so that anyone can understand.
2) Many people are facing graphical glitches in games and other applications which launches full screen by default. Setting no_direct_scanout to true really works. See this discord message link where I helped the guy who was having the same problem - https://discord.com/channels/961691461554950145/961694014615208048/1091369483811160125 . See this video - https://0x0.st/HHLn.mp4
3) Added the regex cheatsheet link. Awesome github repo it explains regex in details ( basic , characters , meta characters , Shorthand Character …
> Did some minor changes to the wiki

- pages/Configuring/XWayland.md
Was having issues getting the hidpi settings to really have any effect. Even after installing the aur hyprland-hidpi package with all the required patches and git reverts, modifying my `.Xresources` `dpi` setting, etc.
What finally helped was this random comment on a [reddit thread](https://www.reddit.com/r/hyprland/comments/10uzsaf/issue_with_resolution/) about modifying the `monitor` setting from `preferred` to `highres`.
Would be helpful to have in the wiki to save other folks time searching imo.
> chore(docs): update hidpi config changes

- pages/FAQ/_index.md
Disclosure: I am the author of wl-screenrec
Add a link to wl-screenrec, a more efficient version of wf-recorder that works for Intel and AMD GPUs.
> Add wl-screenrec as suggestion for screen recording

- pages/Configuring/Dispatchers.md
- pages/Useful Utilities/Clipboard-Managers.md
Again added some minor stuff to the wiki - 
1) It was important to add the [`wl-clip-persists`](https://github.com/hyprwm/hyprland-wiki/commit/765e1a4ab2499ac9554e1234a35758b397440411) program to the wiki. Normally we use wl-clipboard in wayland to store the copied data (for ex text,images) to our clipboard but there is a problem with it. When we close the application from where we copied the data from the data disappears from the clipboard. For example lets say u are using firefox and discord you copy a text from firefox and paste it in discord. Everything works well !! but now try to copy a text from firefox then close the firefox application and now try to paste the text you copied from firefox into discord (or any other application). It doesn't work :cry: . So `wl-clip-persist` is …
> Added some minor stuff again

- pages/Configuring/Variables.md
Add a wiki entry for `swallow_exception_regex` added in [this PR](https://github.com/hyprwm/Hyprland/pull/2026).
> Variables: Add entry for swallow_exception_regex

- pages/Getting Started/Installation.md
Since hyprland is now in Factory, the installation instructions have changed to reflect the new installation process.
> installation: updated openSUSE instructions

- pages/Nvidia/_index.md
just makes it a little less annoying to get up and running with hyprland and nvidia.  covers systemd-boot and grub since theyre the most used (i think).
> Easier nvidia setup

- pages/Configuring/Expanding-functionality.md
- pages/Configuring/Uncommon-tips-&-tricks.md
- pages/Configuring/Using-hyprctl.md
- pages/Contributing and Debugging/_index.md
- pages/FAQ/_index.md
- pages/IPC/_index.md
- pages/Nix/Options & Overrides.md
- pages/Useful Utilities/Status-Bars.md
I noticed that the wiki sometimes uses Bashism in `#!/bin/sh` blocks, so I ran [markdown-shellcheck](https://github.com/Ordoviz/markdown-shellcheck) on it to find more issues.
> Fix shellcheck warnings and optimize code blocks

- pages/Configuring/Variables.md
Changed "curzor_zoom_rigid" -> "cursor_zoom_rigid" documentation to match what's written in the actual codebase 
E.g. https://github.com/hyprwm/Hyprland/blob/28ca434fb52befa2058a6c23b21566c280654e03/src/render/OpenGL.cpp#L148
> Fix: Typo curzor_zoom_rigid -> cursor_zoom_rigid

- pages/Nvidia/_index.md
I kept getting the error `module not found: '***'` for everything I added to my `MODULES` until I used [this solution](https://bbs.archlinux.org/viewtopic.php?id=277580).
> Add tip to install `linux-headers` before running `mkinitcpio`

- pages/Useful Utilities/Status-Bars.md
I'm not sure how to use Eww, so It would be better if someone with better understanding of that added a "How to launch" section under the Eww section.
> Add "How to launch" section under each status bar tutorial

- pages/Useful Utilities/Hyprland-desktop-portal.md
* Changed the suggested overlay from useless-overlay to GURU.
* Bumped qt versions in the docs from 6.4.0 to 6.4.3 since 6.4.0 is not available anymore.
> Update Gentoo installation instructions for XDPH

- pages/Useful Utilities/Hyprland-desktop-portal.md
XDPH doesn't need ** keyword, it means portage will pull in the latest git version of XDPH available, which at the time of writing the wiki may have been required, but is not necessary now.
Removing ** will just pull the latest available package available(i.e assume ~amd64) on the gentoo overlay, which is sufficient.
> Removed the need for XDPH to pull latest git for gentoo

- pages/Configuring/Keywords.md
Also add an example on how to unset a layer rule
> fixed: typo referencing old blurls

- pages/Useful Utilities/Screen-Sharing.md
Recently learned about [xwaylandvideobridge](https://invent.kde.org/system/xwaylandvideobridge) which is a very user friendly way to enable screensharing of Wayland applications and Screens for Apps runnuing under XWayland. 
Since it takes some workarounds to get it working with Hyprland i thought it would be nice to have it documented here since it's currently not described in the gist. 
Please feel free to correct me if i put in some misinformation about Hyprlands ability to hide windows but this was the easiest way i could find.
> add xwayland screensharing documentation

- pages/FAQ/_index.md
Wrappers have been deprecated since 0.23.0, but were not removed from the faq page.
I am not very efficient in markdown, feel free to correct the formatting if there are errors.
> Replace wrapper mention from faq page

- pages/Useful Utilities/Screen-Sharing.md
I assume we're not trying to archive the effect
> fix typo in screen sharing page

- pages/FAQ/_index.md
- pages/Useful Utilities/Hyprland-desktop-portal.md
Improve `xdg-desktop-portals` processes termination since `xdg-desktop-portals` is 19 characters long.
From `killall(1)` man page:
> -e, --exact
>
> Require an exact match for very long names. If a command name is longer
> than 15 characters, the full name may be unavailable (i.e. it is swapped
> out). In this case, `killall` will kill everything that matches within
> the first 15 characters. With -e, such entries are skipped. `killall`
> prints a message for each skipped entry if -v is specified in addition
> to -e.
> Fix: Improve XDP(s) processes termination.

- pages/FAQ/_index.md
programs like flameshot won't capture both of your screens most of the time, so I thought adding a small tutorial to make them work on multimon setups to the FAQ would be helpful.
There is also the matter of flameshot being extremely slow on selection on Hyprland, which I have a workaround for, which might be worth adding but it is a little hacky, so I didn't put it here and it might not even be relevant soon because the workaround already requires compiling a PR (which I would have to create a tutorial for and might not be worth it since it might get merged) and installing a package from the AUR if the user is on Arch Linux. (and so on)
I didn't think it would be appropriate to add it here but if you think I should, I would be happy to add it to this PR.
> Added screenshot utility/flameshot stuff at _index.md

- pages/FAQ/_index.md
When I tried this tip from the wiki to handle monitor connects, I discovered that the event socket is now namespaced with the instance id.
This makes this tip work with version 0.26.0-3 (arch package).
> Add hyprland instance signature to handle_monitor_connect.sh

- pages/Getting Started/Installation.md
It isn't available in the official Void Linux repositories, but I've created template files which can build it using xbps-src consistently: https://github.com/Makrennel/hyprland-void
I figured it'd be good to share it given how many useless issues have been made regarding void linux build problems.
> Add Void Linux Installation tab

- pages/Getting Started/Installation.md
* Changed the Hyprland install instructions to mention the package is now available on the main tree (and because of that it's no longer available in GURU) and added instructions for xdg-desktop-portal-hyprland.
* Added installation instructions for related packages available in GURU.
> Update Gentoo installation instructions

- pages/Configuring/XWayland.md
This commit fixes the broken links to `wlroots-hidpi.patch` and `xwayland-hidpi.patch` on the XWayland page.
The files were moved to patches subdirectory in https://github.com/hyprwm/Hyprland/commit/91e3c654d309c7723bef374cd4d1a0198a16ba53
fixes https://github.com/hyprwm/hyprland-wiki/issues/277
> Fix broken link to `xwayland-hidpi.patch` & `wlroots-hidpi.patch`

- pages/Configuring/XWayland.md
- pages/Nix/Options & Overrides.md
Adresses https://github.com/hyprwm/Hyprland/issues/2867. The patches are no longer supported (I haven't used them for more than a month now, and don't plan on doing so anymore). The `xwayland:force_zero_scaling` option along with toolkit-specific options is the preferred method of achieving scaling for XWayland.
Complements https://github.com/hyprwm/Hyprland/pull/2870.
> XWayland: remove HiDPI patches support

- pages/Useful Utilities/Hyprland-desktop-portal.md
I want to share a little snippet and some instructions to move any incompatible `.portal` files out of `/usr/share/xdg-desktop-portal/portals/` instead of uninstalling them. I personally use this because I want to keep GNOME around and functional and this seems like a less extreme solution than constantly uninstalling/reinstalling `xdg-desktop-portal-gnome`.
> Temporarily disable incompatible portals

- pages/Useful Utilities/Hyprland-desktop-portal.md
The current script could overwrite a newly installed portal with the disabled (and older) version if it is re-enabled after it got updated. This fix removes the disabled version if both exist.
> Fix overwriting newly installed portals with disabled portals

- pages/Nvidia/_index.md
`nvidia-vaapi-driver-git` is no longer a thing in aur
> `nvidia-vaapi-driver-git` >> `libva-nvidia-driver-git`

- pages/Getting Started/Master-Tutorial.md
SDDM >= 0.20.0 has fixed https://github.com/sddm/sddm/issues/1476 and it's no longer necessary to install the lastest development version.
> Master Tutorial: Fix SDDM version requirement

- pages/FAQ/_index.md
I'm using this wl-paste/wl-copy setup to disable middle click, but I've noticed `wl-copy -pc` also clears the selected text in GTK UI elements, which prevents the user from selecting text altogether.
I've found a similar report at https://bugs.kde.org/show_bug.cgi?id=461498. Not sure where the issue lies exactly, but `wl-copy -p ''` accomplishes the same (clearing the primary buffer) without also clearing the selected text.
> Copy empty string into primary clipboard instead of clearing selection

- pages/Configuring/Window-Rules.md
The description as it is can be implied from the name, it's pretty useless without the context. I've just copied that over from dispatchers.
> Doc, window rules: Mention what pin does.

- pages/Getting Started/Installation.md
Instead of going into detail, I felt that it might be best only to link, as even though Slackware is not likely to update very soon the slackbuild itself is lagging behind the most current version by a lot, I did not feel comfortable that the instructions from the build would not deviate. I can provide the detailed instructions if you instead feel that this is incorrect.
> Added a mention to a slackbuild under a new "Slackware" tab.

- pages/Useful Utilities/App-Clients.md
There are some warnings about Spotify not respecting window rules in the docs.
https://github.com/hyprwm/hyprland-wiki/blob/b8de59bf08eec5f1d8103e16744b749ff4315b93/pages/Useful%20Utilities/App-Clients.md?plain=1#L16-L17
As it turns out, Spotify now follows the window rules, e.g., opening in its designated workspace, etc. So, these lines are not needed anymore.
> Remove warnings about Spotify not respecting window rules

- pages/Configuring/Dispatchers.md
Adding a hyperlink to the dispatchers table will make the "Executing with rules" section easier to find.
> add exec with rules hyperlink

- pages/Configuring/Dispatchers.md
- pages/Configuring/Variables.md
- pages/IPC/_index.md
Documentation for hyprwm/Hyprland#3006
New dispatchers:
- `movewindoworgroup`
- `setgrouplockchecking`
New Variables
- `binds:check_group_lock`
- `misc:new_window_in_group`
Removed Variables
- `misc:moveintogroup_lock_check`, replaced by `binds:check_group_lock`
> groups: document `movewindoworgroup` and other changes

- pages/Configuring/Monitors.md
10 bit and screen sharing is a known issue:
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/24
https://github.com/emersion/xdg-desktop-portal-wlr/issues/239
> Add note regarding screen sharing with 10 bit enabled

- pages/Nvidia/_index.md
First PR ever, so here we go:
Nvidia's proprietary drivers include some systemd services to aid with suspend/hibernate and they aren't enabled by default in any of the distros I've seen, and their userspace driver only restores essential memory on wakeup, leading to graphical corruption and crashes, unless their driver is loaded with a specific parameter.
> Nvidia: Add tips to fixing suspend issues

- pages/Configuring/Variables.md
See https://github.com/hyprwm/Hyprland/pull/3528.
> Add option to center the cursor on the focused window when switching workspaces

- pages/Getting Started/Installation.md
Change from 'examples/' to 'example/' to match latest release.
> Fix incorrect paths for Desktop entry and Example Config

- pages/FAQ/_index.md
The `new_optimizations` field was incorrectly nested on the FAQ page.
> Remove unnecessary optimization from FAQ

- pages/Getting Started/Installation.md
In Installation.md, it mistakenly says that Hyprland *does* build against tagged wlroots, when in reality is doesn't.
> Fix typo in Installation.md

- pages/FAQ/_index.md
The default TLP settings caused a lot of stutter and FPS drops when animations ran. It dropped to under 30 FPS from 60 on all animations. 
This was solved by increasing the minimum GPU frequency specified in TLP. I did some tests, it doesn´t seem to have any worse power consumption as the GPU goes into some deeper power-saving when idle anyway, but animations now run perfectly smooth at 60 FPS (which is the refresh rate of my Panel). 
And as it took me a while to figure it out I thought adding it to the FAQ, which I read like 5 times would be worth it.
> Added FAQ item about TLP causing stutter on Intel

- pages/Nix/Hyprland on NixOS.md
The link to the [Hyprland on Home Manager](https://wiki.hyprland.org/Nix/Hyprland-on-Home-Manager/) page in the [Hyprland on NixOS](https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/) page is incorrectly resolving to `https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/Hyprland-on-Home-Manager` 
This changes it so that it correctly resolves to `https://wiki.hyprland.org/Nix/Hyprland-on-Home-Manager`
> Fixes link to Hyprland on Home Manager page (in Hyprland on NixOS page)

- pages/Configuring/Binds.md
Tangentially related to https://github.com/hyprwm/Hyprland/issues/4045. I was researching if anything had changed with regard to bindings and ran across this bit in the docs that is both unclear and seemingly inaccurate. This is my attempt to clarify what keysym names to use as well as fix the inaccuracy.
> binds: Remove inaccurate comment about case and clarify xkb keysym usage

- pages/Nix/Hyprland on Home Manager.md
- pages/Nix/_index.md
Adds instructions on how to use the upstream Home Manager module for Hyprland.
Will probably undergo some changes as the HM module needs a few changes.
Fixes #272
> Nix/HM: add instructions for upstream module

- pages/Nix/Hyprland on Home Manager.md
The link updated externally and the old one no longer goes to the correct place
> Update Home Manager Link on Home Manager.md

- pages/Getting Started/Installation.md
In #271, XDPH was marked as "in the main tree". But in fact XDPH is only available in GURU.
[XDPH in GURU repo](https://github.com/gentoo/guru/tree/master/gui-libs/xdg-desktop-portal-hyprland).
> Fix Gentoo XDPH installation instructions

- pages/Nvidia/_index.md
https://github.com/NixOS/nixpkgs/blob/bd645e8668ec6612439a9ee7e71f7eac4099d4f6/nixos/modules/hardware/video/nvidia.nix#L82
> Nixos nvidia, fix: powerManagement.enable instead of enabled

- pages/Useful Utilities/Status-Bars.md
removes reference to `wlr/workspaces` patch since `hyprland/workspace` should probably be used, and if I remember it correctly the `wlr/workspaces` protocol doesn't even work anymore
> remove waybar wlr/workspaces patch

- pages/Useful Utilities/Screen-Sharing.md
The nofocus rule causes a disgusting behaviour when launching a program with rofi in the workspace where xwaylandvideobridge silently resides, causing it to launch in the last used workspace with an open window instead.
> fix bug caused by xwaylandvideobridge example configuration

- pages/Configuring/Variables.md
Formatted ranges to facilitate scraping on the wiki's Variables.md page.
Ranges are now positioned at the end of the description, enclosed in parentheses, with a "/" separator for lists of options or " - " for ranges.
> Ranges formatted in Variables.md

- pages/Configuring/Dwindle-Layout.md
- pages/Configuring/Master-Layout.md
Formatted ranges to facilitate scraping on the wiki's Configuring pages.
Following up #438
Ranges are now positioned at the end of the description, enclosed in brackets, with a "/" separator for lists of options or " - " for ranges.
> Ranges formatted

- pages/Configuring/Configuring-Hyprland.md
Add a link to variables page underneath the default configuration section to encourage people to read the variables page.
> Add Variables Link to hint under default config section

- pages/FAQ/_index.md
- The trick to disable middle-click paste using `wl-paste` causes huge power consumption
- `wl-paste -p --watch wl-copy -p ''`: Found copied text -> Copy text -> Found copied text -> ...
- Endless loop -> battery 📉
- This PR hides this in a `<details>` and adds a warning/explanation
> Add warning to middle-click disable method in faq

- pages/Configuring/Binds.md
Added example bindings for volume media keys in pages/Configuring/Binds.md in an Examples section at the bottom
> Example Volume Media Key Binds

- pages/Hypr Ecosystem/hypridle.md
- pages/Hypr Ecosystem/hyprpaper.md
Fixes Config Paths For hypridle and hyprpaper:
* `~/.config/hypridle.conf` -> `~/.config/hypr/hypridle.conf` [Source](https://github.com/hyprwm/hypridle?tab=readme-ov-file#configuration)
* `~/.config/hypridle.conf` -> `~/.config/hypr/hyprpaper.conf` [Source](https://github.com/hyprwm/hyprpaper?tab=readme-ov-file#usage)
> Fix Config File Path for hypridle and hyprpaper

- pages/Hypr Ecosystem/hyprlock.md
Simple addition of config file location to wiki. Easier for users to understand where to find config file and more inline with other hyprland-ecosystem packages wiki. Also, noteworthy to mention that without config file hyprlock shows current screen.
> add config info for hyprlock

- pages/Getting Started/Installation.md
As per the title, this PR mentions that hypridle and hyprlock are available on GURU.
> Gentoo installation instructions for hypridle and hyprlock

- pages/Configuring/Variables.md
PR for: hyprwm/Hyprland#3544
Updates:
- touch devices can be unbound with an empty string or the `[[Empty]]` value
- the default for touch devices is `[[Auto]]` where Hyprland will try to get the default output name from wlroots
- tablet input devices don't autodetect an input (wlr doesn't provide a default output name for tablet devices)
> Update the documentation for mapping touch device and tablet inputs to outputs

- pages/Useful Utilities/Screen-Sharing.md
Mr. Powerball253 (or Bruno as I guess he is called) changed his GitHub account name, which broke the link to the screensharing gist. Thankfully, the link still works if with his new GitHub account name. I don't know if he wants his full name in the wiki, so @brunoanc let me know if you want me to change it to something else.
> Fixed a broken link to the screensharing gist

- pages/Useful Utilities/Hyprland-desktop-portal.md
It takes a bit of research to make programs like Firefox use the KDE File Picker with XDPH so i decided to document it here. (inspired by https://github.com/hyprwm/Hyprland/discussions/4988#discussion-6328245)
> document how to use the KDE file picker with XDPH

- pages/Configuring/Expanding-functionality.md
- pages/FAQ/_index.md
- pages/Useful Utilities/Hyprland-desktop-portal.md
- pages/Useful Utilities/Status-Bars.md
I know it's a bit of a nit pick, but copy-paste won't work when trying the examples for eww bar in NixOS.  There are a couple of places in the documentation where `/bin/bash` is referenced (this doesn't exist on NixOS).  For compatibility reasons, I've changed references to `/bin/bash` to `/usr/bin/env bash`.  `/bin/sh` is intact since it isn't an issue.
> Fix bash shebangs for NixOS users

- pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/186
> hyprlock: add `$FAIL` and `$ATTEMPTS` to label section

- pages/Hypr Ecosystem/hyprlock.md
`SIGUSR1` wasn't mentioned anywhere previously, so I added a "User Signals" section.
https://github.com/hyprwm/hyprlock/issues/176
> hyprlock: mention SIGUSR signals

- pages/Configuring/Keywords.md
Remove a hint that suggested the name of the device be written as `device:<device-name>`.
> Remove outdated information

- pages/FAQ/_index.md
Hi, I updated my system recently and noticed that the window rule `nofullscreenrequest` has been [deprecated and removed](https://github.com/hyprwm/Hyprland/commit/7f52db806c149cb3331d6567706e7c19f5a8b692) in favor of `suppressevent`. 
There is still a trace of the old rule in the FAQ/multimonitor screenshot. While updating the doc, I also noticed the first line of the code block was on the same line of the block fence, so it was interpreted as the language and therefore not displayed on the website.
I searched the codebase and found no other occurrences of `nofullscreenrequest` or `nomaximizerequest`, so I guess this should fix it.
> Update deprecated nofullscreenrequest occurrence in FAQ

- pages/Hypr Ecosystem/hyprlock.md
Added `ignore_empty_input` that allows skipping validation when empty password is provided.
> hyprlock: add `ignore_empty_input` and description

- pages/Configuring/Variables.md
Adding `active_area_size` and `active_area_position` variables. https://github.com/hyprwm/Hyprland/pull/5199
> Add graphics tablet active area variables

- pages/Useful Utilities/Other.md
Nvidia drivers supports GAMMA_LUT since version `550.54.14`. Color temperature shifting apps works now.
Read More:
https://www.nvidia.com/download/driverResults.aspx/218826/en-us/
Closes: #557
> remove note about GAMMA_LUT not supported in nvidia

- pages/Configuring/Window-Rules.md
The doc before was wrong on initialclass and is quite confusing, changed the doc from initialClass to initalclass and added warning to make sure this is aware by the reader.
> Update document mistake with initialClass with added warnings

- pages/Configuring/Environment-variables.md
Changes env vars to hyperland format making them copy-pastable into config. 
QT_QPA_PLATFORM is originally in quotes, i think it is because of bash and ``;`` and works in hypr, but i am not sure.
> Change env vars to hyprland format

- pages/Hypr Ecosystem/hypridle.md
This PR fixes a typo in the Hypridle page, and replaces "restor" with "restore."
> Fix typo in `restor`

- pages/Configuring/Using-hyprctl.md
```ini
device:my-epic-keyboard-v1 {
kb_layout=us,pl,de
}
```
does no longer work, but it does work when using
```ini
device {
name=my-epic-keyboard-v1
kb_layout=us,pl,de
}
```
> update switchxkblayout example using name key

- pages/Configuring/Using-hyprctl.md
- pages/Configuring/Window-Rules.md
- pages/Useful Utilities/Screen-Sharing.md
Companion wiki MR for https://github.com/hyprwm/Hyprland/pull/5470.
- Adds info about new `alphafullscreen` and `alphafullscreenoverride` window props and edits examples using `opacity` to account for them.
- Also edited an info card about opacity being a product to note about `override` argument.
> Per-window fullscreen opacity

- pages/Hypr Ecosystem/hyprlock.md
According to https://github.com/hyprwm/hyprland-wiki/issues/579 the wiki was lacking default behaviour, so i quickly added it.
I hope i didn't miss any keyboard shortcuts or input behaviour. I placed it after `Configuration` but before `Widgets` because i don't really know where it fits best. Might aswell move it before `Configuration` since it's default behaviour?
> Add hyprlock default keypress behaviour

- pages/Configuring/Workspace-Rules.md
Wiki MR for hyprwm/Hyprland#5499
- Add `g` flag to `windowCount` prop in workspace selectors.
- Add example for the `windowCount` prop.
> workspace: add group flag in windowCount selector

- pages/Configuring/Window-Rules.md
Documentation for hyprwm/Hyprland#4643
Do I need to add a brief description of how "behind" works in this context or is this fine as-is?
> Add dimaround layer rule

- pages/Configuring/Tearing.md
On AMD I assumed I didn't need the legacy back-end anymore, but seems it is still needed. This just clarifies that it is not supported on the AMD driver as of now. See https://gitlab.freedesktop.org/drm/amd/-/issues/3271
> Expand on tearing section for AMD

- pages/Configuring/Window-Rules.md
`initialtitle` (without capital T) actually matches `title` instead (see https://github.com/hyprwm/Hyprland/issues/5550).
Also explicitly say that the supported fields are only for v2 since they do not work for v1 and I at least oversaw they were listed in the v2 section.
> windowrulev2: fix typo

- pages/Hypr Ecosystem/hyprcursor.md
`--filesystem` instead of `--env`, same as in https://wiki.hyprland.org/FAQ/
> Fix Flatpak override command on Hyprcursor page

- pages/Configuring/Multi-GPU.md
It seems that [wlroots can't](https://github.com/hyprwm/Hyprland/issues/5553) expand the ~ for user home directory, so full path must be used without it.
pinging @kiecla as they initially wrote it and there may be some misunderstanding, assuming it worked for them when it was wrote.
> Remove ~, replace with full path

- pages/Useful Utilities/Must-have.md
fedora stores the polkit executable at a slightly different location, added the path
> Add polkit path on fedora.md

- pages/Configuring/Dispatchers.md
Companion PR for https://github.com/hyprwm/Hyprland/pull/5518.
Adds info about the new rules, a note about default mode & `class:` support, and adds extra info on `floating` & `tiled` matchers.
> Expand on window matching

- pages/Configuring/Environment-variables.md
GDK_BACKEND only supports comma separator. Also added try for any gdk backend after x11.
> GDK_BACKEND separator fix and try any backend

- pages/Configuring/Example-configurations.md
The old links, including the one for the screenshot, are broken, and this patch will fix that.
> Update broken links in Example-configurations.md

- pages/Configuring/Expanding-functionality.md
- pages/Contributing and Debugging/_index.md
- pages/Crashes and Bugs/_index.md
- pages/FAQ/_index.md
- pages/IPC/_index.md
- pages/Useful Utilities/Status-Bars.md
ref https://github.com/hyprwm/Hyprland/pull/5788
> Move /tmp/hypr to $XDG_RUNTIME_DIR/hypr

- pages/Useful Utilities/App-Clients.md
Name of gtkcord4 was changed to dissent by diamondburned. Although the old link still points to the same repo, it would still be better if we changed name as one might try to search it in a browser directly (like me)
> App-Clients: change gtkcord4 to dissent

- pages/IPC/_index.md
Additions to IPC wiki page for the new `togglegroup`, `moveintogroup` and `moveoutofgroup`  ipc events [this is a related PR from hyprland repo 5866](https://github.com/hyprwm/Hyprland/pull/5866)
> IPC: added `togglegroup`, `moveintogroup` and `moveoutofgroup` event infos

- pages/Nvidia/_index.md
Both "nvidia-open" and "nvidia" drivers are proprietary drivers owned by nvidia corporation.
> clarify nvidia drivers

- pages/Nix/Hyprland on NixOS.md
which produced an error when I ran `sudo nixos-rebuild boot --impure --flake /etc/nixos/#`
> add missing semicolon

- pages/Getting Started/Installation.md
Added `hyprwayland-scanner` and `xcb-util-errors` dependencies to _Manual Build_ - _Arch_ section of the _Instalation_ wiki page. (implements #624)
> Installation: updated Arch build dependencies

- pages/Configuring/Binds.md
Added docs for PR [hyprwm/Hyprland#6338](https://github.com/hyprwm/Hyprland/pull/6358) and fixed two code blocks in the binds section that had no highlight.
> Add description to key binds

- pages/Getting Started/Installation.md
Made some changes to make Hyprland easier to install on Void Linux, and updated the guide to reflect that.
> Update installation instructions for Void Linux

- pages/Configuring/Binds.md
- pages/Configuring/Variables.md
In the Binds page:
- I've added the "s" flag for the binds, it's documented in the page but not in the flags list.
- I've also fixed some typos and trailing spaces
In the Variables page:
- The "Mod List" was grouped with the "Colors" in the info callout. I separated them on their own hints.
- Also fixed a typo in the XWayland table.
> Add missing Bind flag and fixed typos

- pages/Nvidia/_index.md
Since disabling hardware cursors is still an important part of having a good time on Hyprland with NVIDIA hardware, it should be better clarified instead of linking to the Variables page with only a warning about WLR_NO_HARDWARE_CURSORS being depreciated.
> added clarification on enabling no_hardware_cursors

- pages/Getting Started/Master-Tutorial.md
Documents nifty NixOS specific environment variable that allows Electron apps to run under Wayland, NixOS is only distro that adds this nifty feature works in all apps I have tested and it is personally what I use. Can be found at https://nixos.wiki/wiki/Wayland
> Document `NIXOS_OZONE_WL=1`

- pages/Configuring/Dispatchers.md
- pages/Configuring/Using-hyprctl.md
I was looking for a way to apply window rules to specific windows using their `pid` because dynamic window rules are unusable with the `exec` dispatcher. 
I found out that `hyprctl setprop` actually supports `pid`. This MR adds the missing documentation based on https://github.com/hyprwm/Hyprland/blob/8a68199a0ceb2894a5d9cc300961c38123ac0312/src/Compositor.cpp#L2296-L2386. 
It also explains to users that dynamic window rules do not work with the `exec` dispatcher and points them to `hyprctl setprop`.
See https://github.com/hyprwm/Hyprland/issues/6653
> Clarify usage of `hyprctl setprop` and `exec` dispatcher with dynamic rules

- pages/Configuring/Dispatchers.md
@fufexan When submitting https://github.com/hyprwm/hyprland-wiki/pull/696 I thought that referencing would work like this https://github.com/hyprwm/hyprland-wiki/blob/33bd679037ce9bba7a11cd202053f671a4d0414c/pages/Configuring/Dispatchers.md?plain=1#L185 because both files are in the same folder. But as I found out now when I clicked on the link in the wiki it doesn't. 
Is this now correct?
> Dispatchers: fix typo

- pages/Nix/Hyprland on Home Manager.md
- pages/Nix/Hyprland on NixOS.md
- pages/Nix/_index.md
Too many people get confused and don't want to enable the NixOS module. This PR changes the wording to emphasize that it is indeed required, and that you still need to install Hyprland if you just use the HM module.
> Update _index.md: emphasize NixOS module requirement

- pages/Nvidia/_index.md
Reword the "Flickering in XWayland games" to recommend the 555 driver alongside the explicit sync patches with the 535xx and earlier drivers being recommended if the GPU is no longer supported. From my experience, using the explicit sync patches requires the 555 driver to work properly with no issues. Now that the 555 driver has been shipped to the mainline arch repos, I reckon it's best to start recommending 555 or later for proprietary driver users first.
> Update _index.md to recommend latest Nvidia driver

- pages/FAQ/_index.md
FAQ about middle click paste is out of date. See https://github.com/hyprwm/Hyprland/issues/6758
> Update middle_click_paste FAQ

- pages/Configuring/Binds.md
The example keybinding for media keys was missing play/pause and skip/back
> Add media keys to example

- pages/Useful Utilities/Clipboard-Managers.md
Hey!
New release introduced using `wl-paste --watch` as the default API for Wayland users. Specifying the shell env caused a delay in image data parsing properly, so removing from the advice as no longer necessary.
thanks.
> docs: update clipse advice after new release

- pages/Getting Started/Installation.md
Makes the section on installing libvirt a bit more reasonable and compact, without really affect what the instructions do
> minor improvements to the vm installation guide

- pages/FAQ/_index.md
Hello,
I had my machine configured to have
full disc encryption,
auto-login in the console (by setting services.getty.autologinUser = "volker" in my nixos configuration file)
auto-login in hyprland.
I thought for long that locking the screen with swaylock would be safe in this configuration, since you can't unlock the screen without the password/fingerprint and you cannot reboot without the FDE password.
Then I realized you can still press "Ctrl + Alt + F3" to get a console where you are logged in (due to services.getty.autologinUser) and i.e. download and run a script.
I nearly got a heart attack and I hope you can imagine how I felt.
I hope this warning might save other people from the same mistake.
See also: https://github.com/swaywm/swaylock/issues/365
> wiki: add screenlocker tty warning

- pages/Configuring/Example-configurations.md
The GitLab repository for the ML4W dotfiles has been archived, as they have been moved to GitHub.
> Replace ML4W Dotfiles link from GitLab to GitHub

- pages/Useful Utilities/Status-Bars.md
Removed "Clicking on a workspace icon does not work!" section. Click seems working out of the box, and no "on-click" option is present in waybar documentation for that module.
Ref. https://man.archlinux.org/man/extra/waybar/waybar-hyprland-workspaces.5.en Also, no reference to sed and Waybar build process are present.
Removed "max-length" from multiple monitor tip, unrelated.
> Refactor waybar section

- pages/Getting Started/Installation.md
Most other distro instructions contain the install command, this brings arch more in line with them.
> installation: add commands to arch instructions

- pages/Useful Utilities/Other.md
The page is somewhat Hyprland specific but since the main page redirects any former X.Org users to the utilities page, I think we should also include some general utilities and compatibility information. Are we Wayland Yet is one of the better sources I know in this regard. Any questions are welcome.
> Adding 'Are we Wayland Yet'

- pages/Getting Started/Installation.md
Alpine keeps an up-to-date package of hyprland in its testing repository.
> Add install instructions for Alpine linux

- pages/Useful Utilities/Must-have.md
This works regardless of where `polkit-kde-authentication-agent-1` is stored and also allows the service to be stopped if needed for whatever reason.
Also change instructions to refer to different init systems rather than different locations for the executable.
> Use plasma-polkit-agent.service rather than launching directly

- pages/Hypr Ecosystem/hyprcursor.md
Makes hyprcursor FAQ redirect goto ../../FAQ instead of ../FAQ (previous one redirected to a nonexistant FAQ page in the Hypr Ecosystem directory)
> fix broken link from Hyprcursor Page to FAQ.

- pages/Configuring/Window-Rules.md
Optionally this could be added too:
```md
{{< callout type=info >}}
`initialClass` and `initialTitle` can also be configured using `initialclass` and initialtitle` respectively.
{{< /callout >}}
```
https://github.com/hyprwm/Hyprland/issues/7420
> remove outdated warning about initialClass case sensitivity

- pages/Hypr Ecosystem/hypridle.md
Just adds `ignore_systemd_inhibit` to the variables table on hypridle page.
> Add ignore_systemd_inhibit variable description for hypridle

- pages/Nix/Hyprland on NixOS.md
Literally spent hours trying to use gsettings like sway suggests before I found it gsettings just doesn't work properly on nixos and you need to use dconf.
If this was written here it would've saved me so much time.
> Mention the use of dconf to fix errors with gtk themes, since gsettings doesn't work and is what the sway devs suggest

- pages/Getting Started/Installation.md
When running yay with sudo, it shows a funny warn `-> Avoid running yay as root/sudo.`. But then it still continues the installtion and run `makepkg` as root and causes error `Running makepkg as root is not allowed`.
> chore: yay command without sudo

- pages/Useful Utilities/Status-Bars.md
Hi, i noticed that the eww widget example for building a status bar, has a problem with the "current" class
example: using this scss code:
``` scss
// workspaces 
.current{
color: $bright_yellow;
}
.occupied {
color: $magenta;
}
.empty {
color: #ffffff ;
}
```
and using the default eww yuck code:
``` lisp
(box :class "workspace-entry ${workspace.id == current_workspace ? "current" : ""} ${workspace.windows > 0 ? "occupied" : "empty"}"
(label :text "${workspace.id == current_workspace ? "󰜋" : "󰜌"}"    ;; characters are rhomboids                
)
) 
```
Generates this bar 
as you can see the "current" class its overwritten by the "occupied" class (same happens with "empty" class), there is no bright yellow color on it.
to fix this we can add another class to the label widget and remove the …
> Update Status-Bars.md to fix an eww widget class problem

- pages/Getting Started/Installation.md
Updated wiki for installing hyprland in ubuntu.
To clarify that Hyprland made it to Ubuntu 24.10 (Unrealeased) universe repo
> updated wiki for Ubuntu installation

- pages/Hypr Ecosystem/hyprlock.md
The default value is already shown in the rightmost column.
> [hyprlock] Remove redundant information

- pages/Configuring/Dwindle-Layout.md
Related to this pull request: https://github.com/hyprwm/Hyprland/pull/7920
> dwindle: add a description for the config option `split_bias`

- pages/Configuring/Using-hyprctl.md
- pages/Configuring/Variables.md
- pages/Configuring/Window-Rules.md
also some minor linting in Variables.md and Window-Rules.md
https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md055.md
https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md031.md
Added sh as language for IconList, so linter wouldnt throw a warning.
> Links between Variables and WindowRules for renderunfocused

- pages/Configuring/Environment-variables.md
- pages/Hypr Ecosystem/xdg-desktop-portal-hyprland.md
I've recently encountered a seemingly not very well documented issue of bad XDG env breaking desktop portal. I specified said issue in wiki so others can have an easier time dealing with this issue
> Specified bad XDG env could break desktop portal

- pages/FAQ/_index.md
Flameshot is a popular and well-featured tool used in X so it's worth mentioning in the FAQ on screenshot tools.
Although it doesn't work out of the box on Wayland, a few windowrules can be added to fix the incompatibility which have been added to the FAQ.
> Add flameshot as a screenshot tool option

- pages/Useful Utilities/Clipboard-Managers.md
- add `cb` clipboard manager: `cb` is a terminal oriented option that has tons of eye candy plus some features other clipboard managers don't have like actually unlimited history and more (oh, and being 100% C++ too :).
- ~~fix "Github" capitalization: GitHub is GitHub, not Github, can't believe nobody else caught this now everything is "Github"~~
> add cb clipboard manager

- pages/Useful Utilities/Clipboard-Managers.md
Corrects the formatting issue, where the 2 sentences are sown in the same line
> add newline

- pages/Configuring/Workspace-Rules.md
Having smart gaps on maximised windows was the behavior of the original `no_gaps_when_only`.
Additionally, it appears that the `w[tg1]` selector does not work. That has been changed to `w[t1]`.
> include smart gaps for maximised windows

- pages/Configuring/Uncommon-tips-&-tricks.md
This PR adds a simple section to the wiki which explains how to reset the F13-F24 keys from their XF86 keysyms back to their expected F13-F24 ones. These are then bindable in programs like OBS.
Please let me know if you have any issues with addition.
> Uncommon tips and tricks: new section to reset F13-F24

- pages/Configuring/Variables.md
Wiki entry for https://github.com/hyprwm/Hyprland/pull/8088
Moved the callout section regarding subcategories, as this is now the first subcategory that users will see when scrolling down the page.
> variables: add the `general:snap` subcategory

- pages/Hypr Ecosystem/hyprlock.md
Having a badly set XDG env variable is currently quite confusing as there is no indication this affects the way hyprlock fades out (but not in).
See hyprwm/hyprlock#521
> hyprlock: Clarify that XDG env can affect the fade out behavior.

- pages/Hypr Ecosystem/hyprpaper.md
-  Added an Installation section to avoid having to visit the Hyprpaper repo if you are on the webpage.
-  Moved the "Run at startup" note to its own section for better visibility.
-  Added a Docs section to link the Hyprpaper repo to the webpage.
> Update documentation for hyprpaper

- pages/Getting Started/Installation.md
about deleted part, I referred to [this commit](https://github.com/hyprwm/hyprland-wiki/commit/3f9b660a37d8cd0e0a3454a4167f2c0a667fb7bb).
> Installation.md: Fix typo and remove old part

- pages/Configuring/Binds.md
Explain why the defaults for the workspaces do not work on a french azerty keyboard, and how to fix it.
Fixes  #810
> [Fix] Hyprland bindings: Improve docs for workspace key binds on non-qwerty keyboards.

- pages/Getting Started/Master-Tutorial.md
Link previously led to https://wiki.hyprland.org/Configuring/Configuring-Hyprland which doesn't exist. 
I think it was meant to point to https://wiki.hyprland.org/Configuring instead.
> Fix 404 in master tutorial

- pages/Getting Started/Installation.md
Hyprland builds perfectly fine without xorg-xinput dep, also It isn't present inside hyprland-git PKGBUILD from aur. Additionally, hyprwayland-scanner, hyprlang and hyprcursor replaced with -git versions to avoid possible errors during build process.
> Manual installation - remove xorg-xinput from required deps

- pages/Useful Utilities/Must-have.md
Most popular notification daemons (namely, dunst, mako, fnott) start automatically via D-Bus activation, whenever a notification is emitted. This is a preferable method, as it allows delaying the daemon startup, until needed, thus slightly speeding up startup.
See https://github.com/emersion/mako https://codeberg.org/dnkl/fnott descriptions. Dunst page doesn't specify it, but from my experience, it also starts with D-Bus activation.
Also, add fnott to examples.
> Notification-daemon - add info about D-Bus activation.

- pages/Useful Utilities/_index.md
Fixed broken link to "Hyprland Desktop Portal" on the Useful Utilities page.
> Fix broken link in Useful Utilities page

- pages/Plugins/Development/Getting-Started.md
There is a broken link in the following section:
https://wiki.hyprland.org/Plugins/Development/Getting-Started/#setting-up-a-development-environment.
I changed it from `../../` to `../../../` as per your recommendation.
> Fixed a broken link in Plugins/Development/Getting-Started

- pages/Configuring/Variables.md
i stumbled on one of `The Linux Cast` video about [tabs in i3](https://youtu.be/sHWYr63mxpg). decided to check if hyprland has similar feature. went through the wiki and found it!
i noticed that the descriptions for the group bar config values were not entirely accurate cos these values actually modify the background color and not the border. so i thought, this was my chance to contribute to Hyprland!
> update description for diff groupbar config values to better reflect their role as background colors and not borders.

- pages/Hypr Ecosystem/hyprlock.md
Ref: https://github.com/hyprwm/hyprlock/pull/548
Mentioning which color options support gradient got a bit messy, so I moved all the documentation for the widget options into tables to be able to specify their type and default values. 
I added details sections to still have an example widget that users can copy directly. I did not build the wiki locally, so I don't know if they look ok.
> hyprlock: document widget options in tables

- pages/Configuring/Workspace-Rules.md
The previous example has an unhandled edge case: when you have exactly one tiled window and one tiled group, it still triggers the no-gaps rule, which I don't think anyone wants
pre-changes:
post-changes:
> fix edge case in smart gaps workspace-rule

- pages/Nix/Plugins.md
`nix search` needs at least one regex to match against: `nix search [option...] installable regex...`
> fix(plugins): missing regex argument for nix search

- pages/Configuring/Dispatchers.md
- pages/Configuring/Environment-variables.md
- pages/Getting Started/Installation.md
- pages/Getting Started/Master-Tutorial.md
- pages/Hypr Ecosystem/hypridle.md
- pages/Hypr Ecosystem/hyprpaper.md
- pages/Hypr Ecosystem/hyprpolkitagent.md
- pages/Useful Utilities/Other.md
- pages/Useful Utilities/Status-Bars.md
- pages/Useful Utilities/Systemd-start.md
https://github.com/hyprwm/Hyprland/pull/8376 and https://github.com/hyprwm/Hyprland/pull/8339 discussion
Probably, need to add another page to mention uwsm with short instructions. Startup or something
Corrections, reviews and suggestions are welcome.
> Add uwsm instructions

- pages/IPC/_index.md
`activemon` appears to be an outdated term used for referring to `focusedmon`
All credits to SoSeDiK for finding this one:
https://discord.com/channels/961691461554950145/1070436481912549497/1305912205392216066
> Changed all instances of activemon to focusedmon

- pages/Configuring/Dispatchers.md
Resort to `terminate-user` only in case of problems with less blanket options.
> Clarify exit command variants

- pages/Configuring/Multi-GPU.md
- pages/Useful Utilities/Systemd-start.md
See https://github.com/Vladimir-csp/uwsm/pull/62#issuecomment-2479742978
@Vladimir-csp pinging for corrections
>  Multi-GPU - Add information- how to export AQ_DRM_DEVICES for uwsm users

- pages/Configuring/Variables.md
Ref.: https://github.com/hyprwm/Hyprland/pull/8476
> Variables: explain that rgb(a) supports hex and decimal values

- pages/Useful Utilities/Systemd-start.md
Replaced the previous NixOS installation option with `programs.hyprland.withUWSM  = true;`.
The [resulting config](https://github.com/NixOS/nixpkgs/commit/04f223946ce67184dfe8d0a0c66b76f6fb91ab3c#diff-2a0030aad6c6a750df9d7404cc5f71bd41e6a3ff0183e5b80c5b79254637e0aaR100-R108) is identical to the previous option written in the wiki, but I'm unsure whether or not we should keep it on the page.
> Systemd-start: use `programs.hyprland.withUWSM` option for NixOS installation

- pages/Useful Utilities/Screen-Sharing.md
This window rule is added to xwaylandvideobridge to prevent it being focused. This is a recommendation to users who use the mentioned package.
> Added a windowrulev2 to Screen-Sharing.md

- pages/Configuring/Binds.md
There was a code block that was wrapping one of the headings which had the effect where the heading would not show as a heading and also the next code block initiator was rendered in plain text.
> docs: fix missing heading due to misplaced codeblock

- pages/Useful Utilities/Status-Bars.md
Seems obsolete.
Even with `layer: bottom` popups render above windows (not behind).
> status-bars: remove obsolete waybar popup faq

- pages/Configuring/Window-Rules.md
Window rules added here: https://github.com/hyprwm/Hyprland/pull/8655
> Window-Rules: add descriptions for `scrollmouse` and `scrolltouchpad`

- pages/Getting Started/Preconfigured-setups.md
As the author of end-4/dots-hyprland, I feel I cannot maintain it well for now and would like to have it removed from the wiki, at least temporarily, to not cause new users any issues.
> preconfigured setups: remove end-4/dots-hyprland

- pages/Configuring/Binds.md
ref. https://github.com/hyprwm/Hyprland/issues/8672
> binds: add nested submaps example

- pages/Hypr Ecosystem/hyprlock.md
Document the stuff added in hyprwm/hyprlock#583.
> hyprlock: document background reloading options

- pages/Configuring/Window-Rules.md
Updating for this breaking change:
https://github.com/hyprwm/Hyprland/issues/8424#issuecomment-2546828791
While I was at it, removed parentheses and the use of `^$` from most examples except the ones where I feel parentheses help with readability.
Also, out of curiosity, why was this change made? I think RE2 has `PartialMatch` so just wondering.
> Configuring/Window-Rules: callout that regexes need a full match

- pages/Hypr Ecosystem/hyprlock.md
Someone asked for support for this and then I realized it already works nicely.
> hyprlock: document float support for layoutxy

- pages/Getting Started/Installation.md
I was getting the following error when trying to build until I installed glaze from AUR:
```
CMake Error at hyprpm/CMakeLists.txt:13 (find_package):
By not providing "Findglaze.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "glaze", but
CMake did not find one.
Could not find a package configuration file provided by "glaze" with any of
the following names:
glazeConfig.cmake
glaze-config.cmake
Add the installation prefix of "glaze" to CMAKE_PREFIX_PATH or set
"glaze_DIR" to a directory containing one of the above files.  If "glaze"
provides a separate development package or SDK, be sure it has been
installed.
-- Configuring incomplete, errors occurred!
make[1]: *** [Makefile:15: release] Error 1
make[1]: Leaving directory …
```
> Added glaze to packages needed for manual installation on Arch

- pages/Configuring/Binds.md
Add a valid window parameter to the out-of-date examples.
> Update global keybinds examples

- pages/Configuring/Master-Layout.md
- Replaced boolean config parameter `always_center_master` to an integer value `slave_count_for_center_master` for center orientation of master layout.
- Default behavior is unchanged with new default value 2.
[Related Source Modification](https://github.com/hyprwm/Hyprland/pull/8871/files)
I hope i've not misunderstood something.
Cheers!
This is a single line change which effects the wiki in following way:
| name | description | type | default |
| --- | --- | --- | --- |
| always_center_master | when using orientation=center, keep the master window centered, even when it is the only window in the workspace. | bool | false |
| name | description | type | default |
| --- | --- | --- | --- |
| slave_count_for_center_master | when using orientation=center, make the master window centered …
> Replaced always_center_master to slave_count_for_center_master

- pages/Useful Utilities/Clipboard-Managers.md
The manager `cb` does not support Wayland. The version available in AUR renders the entire desktop unusable by spawning invisible windows which cause focus loss and repositioning of all windows every ~2 seconds. Does not work with `wl-paste --watch` either.
> Clipboard-Managers: remove broken manager

- pages/Hypr Ecosystem/hyprlock.md
Without a config, hyprlock fails with:
```
[CRITICAL] ConfigManager threw: Could not find config in HOME, XDG_CONFIG_HOME, XDG_CONFIG_DIRS or /etc/hypr.
```
This was mentioned in https://github.com/hyprwm/hyprlock/issues/450 and closed with
>  hyprlock with no config is more confusing than anything, as it will not render anything
So I'm assuming this is behaving as expected and the docs just need to be fixed.
> Document that hyprlock config is required.

- pages/Configuring/Variables.md
- pages/Configuring/Window-Rules.md
Document features added in Hyprland PR [#8943](https://github.com/hyprwm/Hyprland/pull/8943).
> Document `decoration:rounding_power` and window rule `roundingpower`

- pages/Getting Started/Master-Tutorial.md
It's not very clear that the two links lead to different locations. This change makes it more obvious.
> Getting Started:Master-Tutotial - Improve clarity of FAQ links in cursor setup documentation

- pages/Configuring/Binds.md
In https://wiki.hyprland.org/Configuring/Binds/, the hyperlink on the sentence
- "If you want to access your description you can use `hyprctl binds`. For more information have a look at **Using Hyprctl**" 
is as pointing to a non-existent location. That is because it points to https://wiki.hyprland.org/Configuring/Using-hyprctl.md when it should point to https://wiki.hyprland.org/Configuring/Using-hyprctl  (no .md at the end).
> fix: hyperlink to 404 page had an extra .md at the file name

- pages/Nix/Hyprland on Home Manager.md
Since this code is meant to be copied, this typo is particularly annoying.
> Fix typo in Hyprland on Home Manager.md

- pages/Getting Started/Installation.md
Both Hyprland and aquamarine build and work fine without seatd dependency.  Also, [the related discussion](https://github.com/hyprwm/Hyprland/discussions/8421#discussioncomment-11216306)
> Getting Started/Installation: remove seatd dependency under 'Manual - Arch' section

- pages/Getting Started/Installation.md
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/73256
The package have been moved to community repository and it have been already released on 3.21.
Community repository is enabled by default.
> Installation: Alpine package have been moved from testing

- pages/Nix/Hyprland on Home Manager.md
Following the introduction of `xdg.portal` settings in Home Manager, it's now possible to set `wayland.windowManager.hyprland.package` to `null`.
One issue I (as well as a couple of others in the Hyprland Discord) encountered, was not realising that without manually setting `wayland.windowManager.hyprland.portalPackage = null` in our configs as well, we'd encounter a broken XDPH caused by using the Hyprland Flake for both Hyprland and XDPH in our NixOS configurations, and then overwriting our XDPH with `nixpkgs` upstream of XDPH in Home Manager.
This adds a section on how to set the Home Manager `package` and `portalPackage` to `null` without causing any issues relating to mixing versions of Hyprland and XDPH.
> home-manager: clarify setting HM package to `null` on NixOS

- pages/Hypr Ecosystem/hyprpaper.md
This PR rewrites and extends the `reload` keyword hyprpaper documentation.
This section was originally very short, with no example provided and only a very short description, this led to a lot of people missing this option and instead going with the old "unload, preload, set" combo which isn't needed and probably causes issues with the transition.
Examples of people missing this config option is seen in the discord server and hyprpaper issue tracker:
https://canary.discord.com/channels/961691461554950145/1215490894804029450/1335447955339087882
And I also missed it too when i first started using hyprpaper.
I also added a small piece of documentation about how to randomize your wallpaper using the `reload` keyword. This is in response to https://github.com/hyprwm/hyprpaper/issues/194 where …
> Hypr Ecosystem/hyprpaper: rewrite `reload` docs

- pages/Configuring/Multi-GPU.md
hyprwm/Hyprland#9284 related
clarifies that AQ_DRM_DEVICES not only sets gpu priority, but is also basically a whitelist
> Update Multi-GPU to clarify AQ_DRM_DEVICES

- pages/Nvidia/_index.md
Clarifies that DRM kernel mode setting now enabled by default on drivers newer than version 560.35.03-5 and adds a small command to check if its already enabled.
[Source](https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting)
ref #968
> nvidia: update DRM kernel mode setting section

- pages/Getting Started/Installation.md
Added ```libxcursor``` dependency to <em>Manual Installation - Arch<em>
> Installation: add missing dependency for Arch

- pages/Hypr Ecosystem/hyprsunset.md
Since hyprsunset now can be controlled via IPC, it makes sense to autostart it with the rest of the session. 
Also, https://github.com/hyprwm/hyprsunset/pull/19
> Hypr-Ecosystem/hyprsunset: add 'run at startup' section

- pages/Useful Utilities/Status-Bars.md
Used to make sense with 
```
Then, in `~/.config/waybar/config` replace all the references to `sway/workspaces` with `hyprland/workspaces`.
```
but now since the instruction for that is written below, it leaves an unnecessary instruction.
edit: added commentary to pr
> Useful Utilities/Status Bars: remove unclear waybar config instruction

- pages/Hypr Ecosystem/hyprlock.md
Hi team,
First PR here. Let me know if you need some CLA/MSA/NDA etc.
- Add System Configuration section pointing users to pambase and faillock to tweak retry/lockout params.
Like every good Arch user, I own a cat. He loves to walk on my keyboard. When that happens I get locked out. I initially wanted to patch hyprlock with some config options, but found out there's already a knob for all of this. Sharing to spare others pain.
Source: https://wiki.archlinux.org/title/Security#Lock_out_user_after_three_failed_login_attempts
> Hypr Ecosystem/hyprlock.md: Point to pambase and faillock

- pages/Configuring/Dispatchers.md
This is a WIP and needs feedback to clarify a few things. Specifically whether fullscreen is planned for deprecation and the functionality of state 3 "maximize and fullscreen."
> dispatchers: add documentation for fullscreenstate

- pages/Hypr Ecosystem/hyprlock.md
It looks like no_fade_out option is not available in hyprlock anymore, therefore that warning should be useless.
> hyprlock: remove no_fade_out warning

- pages/Configuring/Variables.md
- pages/Configuring/XWayland.md
In follow to hyprwm/Hyprland#9615
* add information about `xwayland:create_abstract_socket`
* add brief description of the abstract unix socket issue
> XWayland: add the abstract Unix socket description and new variable information

- pages/Hypr Ecosystem/hyprlock.md
Adds documentation for [https://github.com/hyprwm/hyprlock/pull/625](https://github.com/hyprwm/hyprlock/pull/625)
> hyprlock: add documentation for `auth:fingerprint:retry_delay`

- pages/Nix/Hyprland on Home Manager.md
The package gnome.adwaita-icon-theme was moved to a top-level package.
> Update iconTheme example

- pages/Configuring/Variables.md
Adds two new groupbar settings:
group:groupbar:keep_upper_gap - allows to keep or remove upper outer gap
group:groupbar:text_offset - allows to adjust vertical alignment for text in a group bar
All settings are defaulted to values that keep current layout AS IS.
Demo video:
https://github.com/user-attachments/assets/dbae0131-a786-4861-94c8-7a6e55d7a65d
PR with implementation:
https://github.com/hyprwm/Hyprland/pull/9733
> Groupbar: add text_offset and keep_upper_gap settings

- pages/Contributing and Debugging/Issue-Guidelines.md
This is a draft for the new issue guidelines. They are inspired by Ghostty's approach.
Our issues are unmaintainable on Hyprland. Let's fix this.
Comments welcome, reviews welcome.
TL;DR: We are banning opening issues, and instead, people open discussions. Members can "promote" discussions to issues.
All existing issues under Hyprland would be closed with this coming into effect.
BEFORE EFFECTIVE CHECKLIST:
AFTER EFFECTIVE CHECKLIST:
> Draft, Discussion, RFC: New Issue Guidelines for Hyprland.

- pages/Configuring/Animations.md
I just learnt that windows can have different animations for `windowsIn` and `windowsOut` in this discussion https://github.com/hyprwm/Hyprland/issues/9894#issuecomment-2804920126
AFAIK this feature was not documented, this PR simply describes this feature in the anim tree docs
> animations: document anim style for windowsIn and windowsOut

- pages/Configuring/Variables.md
Adds missing `misc:vrr` mode from [#9334](https://github.com/hyprwm/Hyprland/pull/9334)
> Add missing VRR mode documentation

- pages/Configuring/Multi-GPU.md
The current command with `grep VGA|3D` doesn't show my integrated intel graphics. `::03xx` is all PCI devices of class 'display controller'
```console
> lspci -d ::03xx
00:02.0 Display controller: Intel Corporation AlderLake-S GT1 (rev 0c)
01:00.0 VGA compatible controller: NVIDIA Corporation GA102 [GeForce RTX 3080 Ti] (rev a1)
```
> Update multi-gpu lspci instructions to include all display controllers

- pages/FAQ/_index.md
Screen sharing section already asked user to install `xdg-desktop-portal-hyprland`. But FAQ section's config is still the 3-year-ago version. 
For users new to Hyprland might feel confused about the inconsistent name.
> FAQ/_index.md: Update xdph script

- pages/Configuring/Binds.md
- pages/Configuring/Variables.md
I moved parts mentioning `input:drag_threshold` to now mention `binds:drag_threshold` because `input:drag_threshold` doesn't exist. Also corrected the example config given in Binds.md
See [Hyprland Discussion #10180](https://github.com/hyprwm/Hyprland/discussions/10180)
> Variables and Binds: correct input:drag_threshold to binds:drag_threshold

- pages/FAQ/_index.md
Hello,
VRR's flickering can somewhat be mitigated by widening or reducing the VRR range.
Having VRR enabled all the time can help desktop smoothness for some reason I don't understand, making this trick useful in some cases.
For instance, I fixed my year-old flickering by changing my monitor's VRR range from [48, 144] to [60, 144] in my EDID.
It looks like getting too low on refresh rate can trigger funny behaviours on poorly-designed monitors, so highering the lower boundary of VRR range can prevent this behaviour.
On the contrary, I saw somewhere that widening this range can lower the limit refresh rate triggering this issue, no clue why though.
I really wanted to have VRR enabled all time because it makes my desktop way smoother, whatever mininum GPU frequency, CPU governor or hyprland …
> Added instructions to mitigate VRR's brightness flickering

- pages/Configuring/Window-Rules.md
Added callout notifying users of the relation between the fullscreen outputs of the `hyprctl clients` command and the fullscreen configs in window rules
See https://github.com/hyprwm/Hyprland/pull/10190 for more info
> Configuring/Window-Rules: Add fullscreenclients callout

- pages/Nix/Cachix.md
For a substituter to be used, [one of the following has to be met](https://nix.dev/manual/nix/2.24/command-ref/conf-file.html#conf-substituters):
- the substituter is under the trusted-substituters list
- The user calling Nix is in the trusted-users list
I think it is better to recommend adding hyprland.cachix.org as a trusted substituter, rather than adding to the trusted-users list, but at least one of these needs to be done for the substituter to be used.
> Nix/Cachix: improve substituters documentation

- pages/Nix/Hyprland on NixOS.md
updates wiki to use new definitions that were deprecated in nix
from Nix:
```
evaluation warning: `mesa.drivers` is deprecated, use `mesa` instead
evaluation warning: `mesa.drivers` is deprecated, use `mesa` instead
evaluation warning: The option `hardware.opengl.package32' defined in `/nix/store/5rayqqq26jfw48hqbyxh2lxmbm12pq0l-source/nixos/configuration.nix' has been renamed to `hardware.graphics.package32'.
evaluation warning: The option `hardware.opengl.package' defined in `/nix/store/5rayqqq26jfw48hqbyxh2lxmbm12pq0l-source/nixos/configuration.nix' has been renamed to `hardware.graphics.package'.
evaluation warning: The option `hardware.opengl.driSupport32Bit' defined in `/nix/store/5rayqqq26jfw48hqbyxh2lxmbm12pq0l-source/nixos/configuration.nix' has been renamed to …
```
> Nix/Hyprland on NixOS: update deprecated definitions

- pages/Hypr Ecosystem/hyprlang.md
This is documentation for the expression escaping that would be added from [this](https://github.com/hyprwm/hyprlang/pull/76) pull request.
It assumes the version number will be 0.6.4.
> Documentation for hyprlang expression escaping.

- pages/Configuring/Uncommon-tips-&-tricks.md
currently if 1 floating window is behind another floating window, if you select the window behind it focuses it but it stays behind.
this pr fixes this issue
> alttab : add altzorder top

- pages/Configuring/Variables.md
I use these to automatically generate data for [HyprLS](https://github.com/hyprland-community/hyprls)
Of course, it's up to me to adapt my kinda-ugly scraping to your changes and not the other way around, but I figured It'd be easier for me to add these everywhere upstream instead of like, trying to infer the group name from the heading or something
> Variables: explicitly mention the subcategory name for each subcategory

- pages/Configuring/Uncommon-tips-&-tricks.md
I want people to know that many options exist for Caps Lock in `kb_options`, so I made the docs regarding Caps Lock a bit clearer.
> docs: Improve docs regarding Caps Lock remapping

- pages/Getting Started/Installation.md
- pages/Nix/Hyprland on Home Manager.md
- pages/Nix/Hyprland on NixOS.md
- pages/Nvidia/_index.md
- pages/Useful Utilities/Systemd-start.md
fixes syntax highlighting and is more correct 👍🏽 
before it looked like below in a few places 👇🏽 
maybe i missed some but I think I caught em. Checked each Nix codeblock with 
```sh
git grep \`\`\`nix
```
but I could've left one who knows
> treewide: add missing curlies to some Nix language codeblocks

- pages/Useful Utilities/Systemd-start.md
Not sure if this is only on my system or true for everyone, but hyprland.desktop does not exist on my computer and the correct entry is hyprland-uwsm.desktop.
Thus creating this pull request in case others might get locked out by their shell profile because of this.
> UWSM: Fix hyprland's UWSM entry name

- pages/Configuring/Variables.md
Hyprland does not work with the decimal version of rgba() and rgb() when they have spaces inbetween the numbers, so here a change to the wiki to explain this as its a little confusing at the moment, maybe im stupid but i feel like this is a good change (don't mind the commit descriptions)
> Remove spaces in rgba and rgb decimal value's and added explanation

- pages/Getting Started/Master-Tutorial.md
Hello. Recently new to Hyprland and in my search for a login manager I ended up choosing [ly](https://github.com/fairyglade/ly). The [Launching Hyprland](https://wiki.hypr.land/Getting-Started/Master-Tutorial/#launching-hyprland) section of the Master Tutorial states that for login managers:
> - ly -> Works poorly.
I've opened this PR to see whether we think this is still the case and a proposed change based on current findings/experiences. From the wiki I initially uninstalled ly assuming it would be difficult to setup and get working, but after a bit of digging I found a [Reddit thread](https://www.reddit.com/r/NixOS/comments/17ngiji/how_do_i_get_ly_working_on_hyprland/) from 2 years ago where another Hyprland user found ly to be working out of the box. After reinstalling and giving it …
> Getting Started/Master Tutorial: Update Launching Hyprland section - list of compatible login managers

- pages/Useful Utilities/Status-Bars.md
The install guide points to a 404. The project scope recently changed slightly, and the structure of the Astal docs has also been updated as a result.
> Update Astal urls

- pages/Configuring/Binds.md
adding commas for multiple bind passes as valid config but does not work as expected.
ref: https://wiki.hypr.land/0.49.0/Configuring/Uncommon-tips--tricks/#minimize-windows-using-special-workspaces
> Configuring/Binds: remove extra commas for multiple bind

- pages/Useful Utilities/Screen-Sharing.md
`bitdepth` setting on hyprland configuration should match that of the physical monitor. Screenshare was not working for me for a long time because of this simple mismatch. Many (old) sources on reddit and github mention changing bitdepth as one of the first options for fixing the problem when in reality it could be caused by something else.
> Screensharing: add bitdepth information

- pages/Configuring/Variables.md
Latest hyprland [release](https://github.com/hyprwm/Hyprland/releases/tag/v0.50.1) defaults drag_lock to 0
Wiki needs an update.
> configuring/variables: change drag_lock default to 0

- pages/Configuring/Variables.md
some subcategories had trailing underscores, as they were defined as subcategory instead of _subcategory
> fix subcategory typos

- pages/Useful Utilities/File-Managers.md
The linked GitHub repo was last updated 14 years ago, and the pacman thunar package is using this gitlab link, if I'm not mistaken (https://gitlab.archlinux.org/archlinux/packaging/packages/thunar/-/blob/main/PKGBUILD).
> Useful Utilities/File-Managers.md: fix Thunar link

- content/Configuring/Window-Rules.md
Resolves: #1140 
This assumes that *ALL* types of window rules are evaluated from top to bottom, correct me if I'm wrong.
> Configuring/Window Rules: Warn about evaluation order

- content/Configuring/Environment-variables.md
- Add warning type to callout about avoiding quotes (also reword warning).
- Add examples of variable with multiple values and different formats/value separators.
- Minor punctuation fixes.
Note: `py` syntax highlighting was used for the code blocks instead of `ini` to avoid visualizing `";xcb"` as a comment.
Retry of #1170 because I f'd up the rebase.
Resolves #171
> Configuring/Environment-variables: Add usage examples

- content/Useful Utilities/App-Launchers.md
rofi supports wayland natively since 2025. old repo will be archived.
> rofi wayland support

- content/Hypr Ecosystem/hyprpaper.md
Warn the user that explicitly setting a monitor for a wallpaper, won't be overridden when using wildcard monitor.
- Related issue: https://github.com/hyprwm/hyprpaper/issues/258
> Update hyprpaper.md: Add warning

- content/Configuring/Uncommon-tips-&-tricks.md
Update hyprland docs example for gamemode.sh to incude:
- `animation borderangle,0` <- Disable border animation
fixes loop style for borderangle stress on CPU/Battery (further read: hyprwm/hyprland#4779 )
- `keyword decoration:fullscreen_opacity 1;` 
Games in fullscreen would probably want this set
- `hyprnotify` notification on gamemode state on toggle
- exit codes reflect successfull state change (0) or error (!= 0)
> Update Uncommon-tips-&-tricks.md - gamemode.sh 

- content/Hypr Ecosystem/hyprsunset.md
Hypr Ecosystem/hyprsunset: correcting the description of identity
The previous description is wrong. This change corrects it.
> Hypr Ecosystem/hyprsunset: correcting the description of identity

- content/Contributing and Debugging/Issue-Guidelines.md
Fixes the following error which occurs when running `hugo serve` (v0.148.2):
```Error: error building site: process: readAndProcessContent: ".../hyprland-wiki/content/Contributing and
Debugging/Issue-Guidelines.md:42:1": got positional parameter 'To'. Cannot mix named and positional parameters```
> Fix syntax causing hugo serve error

- content/Configuring/Master-Layout.md
Update `focusmaster` dispatcher command's params section to include the new `previous` parameter value introduced in https://github.com/hyprwm/Hyprland/pull/11361
> Master-Layout: document `previous` param value for `focusmaster` command

- content/Hypr Ecosystem/hyprlock.md
Add cli args to the documentation.
They have been absent from the documentation so far.
Ref: https://github.com/hyprwm/hyprlock/issues/857
> hyprlock: document cli arguments

- content/Useful Utilities/Clipboard-Managers.md
No hard feelings if this isn't wanted, but I made an [alternative](https://github.com/Rolv-Apneseth/clipvault) to `cliphist` and thought it would be cool to include it here, as this is where I originally found `cliphist` too. Thank you all for the great resource that is the Hyprland wiki.
> Useful Utilities/Clipboard-Managers: add `clipvault`

- content/Hypr Ecosystem/hyprlock.md
> meaning you will just see your screen
not true since Hyprland 0.50.
Thus updated the text a bit.
> hyprlock: update warning about empty config to latest hyprland behaviour

- content/Configuring/Gestures.md
- content/Configuring/Variables.md
In the last [update](https://github.com/hyprwm/Hyprland/releases/tag/v0.51.0), three options essential for laptop/trackpad users were removed, rendering us unable to change workspaces using trackpad. I read the release notes here on GitHub to find out [why](https://github.com/hyprwm/Hyprland/pull/11490).
Still, the 1:1 replacement for workspace swipe gesture isn't on the gestures page. (`gesture = 3, horizontal, workspace`)
This PR adds that as an example, plus the removal info on the Variables page.
PS: thanks for the gestures, love them being 1:1
> Add info about workspace swipe gestures

- content/Configuring/Example-configurations.md
[illogical-impulse](https://github.com/end-4/dots-hyprland) has been updated, and the old screenshot is of the old AGS verion of illogical-impulse, which has been deprecated.
This PR uses the URL of the latest screenshot, same as the one on the [Homepage](https://ii.clsty.link).
> Update image link of illogical-impulse in Example-configurations.md
