pages/Configuring/Basic-Config.md
=> fix CTLR instead of CTRL

pages/Getting Started/Quick-start.md
Just started reading wiki and found some typo. Hope to be fixed soon.
=> fixing typo

pages/Getting Started/Installation.md
Signed-off-by: Aisha Tammy <floss@bsd.ac>
=> add installation instructions for gentoo

pages/Configuring/Advanced-config.md, pages/Configuring/Basic-Config.md
Additions as per the changes made in [this pull request.](https://github.com/hyprwm/Hyprland/pull/352).
=> docs for prev workspace switch (Hyprland PR #352)

pages/Getting Started/Installation.md
this should be clear (and concise) enough
=> inform people about the cleaninstall task

pages/Nvidia/_index.md
Sorry for the formatting mistakes last time.
=> Add instructions to enable Nvidia cards

pages/FAQ/_index.md
Both of these options seem to be needed. So changing OR to AND seems preferable.
=> Update FAQ from OR to AND

pages/Configuring/Advanced-config.md
This adds instructions for this pull request:
https://github.com/hyprwm/Hyprland/pull/706
=> add instructions for highrr and highres rules

pages/Configuring/Variables.md
Complements https://github.com/hyprwm/Hyprland/pull/787
=> Variables: add accel profile and scroll method

pages/Useful Utilities/Wallpapers.md
This pr adds mention of `swww` to `Useful\ Utilities/Wallpaper.md`
=> feat: mention of `swww`

pages/Configuring/Window-Rules.md
Documentation entry for `maxsize` window rule.
=> add maxsize

pages/Home.md
Quick fix for a syntax error in `Home.md`.
=> Fix wrong syntax

pages/Configuring/Binds.md, pages/Configuring/Dispatchers.md
yeah just the title, wish you a good day/night
=> explained how to use multiple dispatchers with the same keybind

pages/FAQ/_index.md
this package doesn't come as a dependency (technically it's not coz most of ppl use xorg) but even tho OBS  can't work with out
=> Added a needed package for obs

pages/Configuring/Using-hyprctl.md
Counterpart to https://github.com/hyprwm/Hyprland/pull/990.
=> Add note on passing arguments to exec.

pages/Configuring/Window-Rules.md
Add the bordercolor rule. I hope I have the link to variables#variable_types correct. I do not know how to test it.
=> Bordercolor rule

pages/Configuring/Window-Rules.md
* Add _fullscreen_ and _pinned_ as matching variable
* describe dynamic rules
=> Describe dynamic rules

pages/Configuring/Window-Rules.md
Wiki entry for https://github.com/hyprwm/Hyprland/pull/1107
=> add nofullscreenrequest rule

pages/Configuring/Uncommon-tips-&-tricks.md, pages/Configuring/Using-hyprctl.md
```
❯ hyprctl --help                                    
usage: hyprctl [(opt)flags] [command] [(opt)args]
commands:
.....
switchxkblayout
.....
```
=> `setxkblayout` is actually `switchxkblayout` in `hyprctl`

pages/Contributing and Debugging/_index.md
Added missing $ character to the log view command copy-paste
=> Missing $ char added

pages/Configuring/Master-Layout.md
This is the documentation for hyprwm/hyprland#1059 and https://github.com/hyprwm/Hyprland/pull/1202
=> master layout: documented orientation (hyprwm/hyprland#1059)

pages/Configuring/Master-Layout.md
documentation for hyprwm/Hyprland#1213
=> Documented inherit_fullscreen (hyprwm/Hyprland#1213)

pages/Useful Utilities/Must-have.md
simple typo, should be authentication not authentification
=> correct polkit command

pages/Useful Utilities/Status-Bars.md
Don't know if this is the kind of thing you want in the wiki, but I've been using these widgets for a while and figured they might be useful to others?  If you like the idea but want it organized differently or want more or less details just let me know, I just dropped it in the status bars -> eww section as a "this seems reasonable".
=> Add example eww widgets for workspaces and active window

pages/Useful Utilities/App-Launchers.md
Just finished awesome-hyprland, and thought it might work to replace the removed awesome-wayland in #66
=> Re-add an awesome list

pages/Nix/_index.md
I tried to fix broken link in #91 but made another broken one, this is to fix that, sorry
=> fix broken link

pages/Configuring/Dispatchers.md
Following https://github.com/hyprwm/Hyprland/commit/3173fbdc4a2b0a306cf56e282524bcb33914ab96
=> feat: add renameworkspace dispatcher doc

pages/Configuring/Uncommon-tips-&-tricks.md
Fix small typo: kaybind -> keybind
=> Fix small typo: kaybind -> keybind

pages/Configuring/Uncommon-tips-&-tricks.md
=> A way to minimzie Steam to tray instead of killing

pages/Configuring/Dispatchers.md
with https://github.com/hyprwm/Hyprland/pull/1402
=> feat: add focusurgentorlast dispatcher doc

pages/Configuring/Example-configurations.md
why did you have to pick my oldest rice for the preview
=> change preview image for dotfiles

pages/Nvidia/_index.md
I did just what I added on top of the other instructions for Nvidia and it worked for me. Could be very useful to others.
=> Added fix instructions for hybrid graphics devices

pages/Configuring/Variables.md
Hello, if i'm not mistaken `on` and `off` should count as accepted boolean vlaues.
cf. https://github.com/hyprwm/Hyprland/blob/main/src/helpers/MiscFunctions.cpp#L530
=> Add accepted boolean values

pages/Configuring/Example-configurations.md
mine looks different, hope it will be in this list
=> add one more screenshot to examples

pages/Configuring/Monitors.md
Changed the ordering so that it aligns with the first part of the sentence.
=> Edit Monitor.conf

pages/Configuring/Variables.md
related feature PR: https://github.com/hyprwm/Hyprland/pull/1347
=> add options related to `resize_on_border`

pages/Getting Started/Installation.md
People are having problems compiling the wayland-desktop variant
=> Switch from ``wayland-desktop`` to ``guru`` overlay

pages/Nvidia/_index.md
I was facing problems with Discord and Zoom screen sharing, and this worked for me.
=> Note for Discord and Zoom screen sharing on Nvidia

pages/Configuring/Master-Layout.md
Take a look and see the descriptions are clear enough.  I tried to match the verbosity of the existing text.
=> Updated Master-Layout.md with center orientation

pages/Contributing and Debugging/_index.md, pages/Plugins/Development/Advanced.md, pages/Plugins/Development/Getting-Started.md, pages/Plugins/Development/Plugin-Guidelines.md, pages/Plugins/Using-Plugins.md
Added wiki pages for using and creating plugins (https://github.com/hyprwm/Hyprland/pull/1590)
=> Plugin System Pages

pages/Configuring/Variables.md
Wiki entry for: https://github.com/hyprwm/Hyprland/pull/1658
=> Add animate_mouse_windowdragging entry

pages/Configuring/Monitors.md
* Added command to show available monitors
=> Updated monitor configuration documentation

pages/Configuring/Uncommon-tips-&-tricks.md
I was getting worse performance than sway with wine applications, and I would like to share what fixed this for me.
=> Add animations/blur/etc toggle script

pages/Plugins/Using-Plugins.md
my dumb ass got stuck on this for about 5 minutes so I'm guessing eventually someone will ask about this, better to have it on the wiki
not sure why it changed that last line, I didn't edit anything besides the hint
=> add tip about plugin path

pages/Useful Utilities/Status-Bars.md
Fixes https://github.com/hyprwm/hyprland-wiki/issues/127
[![Packaging status](https://repology.org/badge/vertical-allrepos/waybar-hyprland.svg?header=waybar-hyprland)](https://repology.org/project/waybar-hyprland/versions)
=> Fix Waybar instructions on FreeBSD

pages/Configuring/Dispatchers.md, pages/Configuring/Variables.md
=> Add `swapwindow` and `no_focus_fallback` docs

pages/Configuring/Window-Rules.md
Relates to pull request:
https://github.com/hyprwm/Hyprland/pull/2043
=> Add entry for fakefullscreen windowrule

pages/Configuring/Dispatchers.md
hyprland pull: hyprwm/Hyprland#2100
=> Added moveCursor dispatcher

pages/Configuring/Variables.md
=> Fix default empty string value [Empty] -> [[Empty]]

pages/Configuring/Variables.md
Companion pr for hyprwm/hyprland#2135
=> Add docs for `mouse_refocus` (hyprwm/hyprland#2135)

pages/Configuring/Monitors.md, pages/Configuring/Workspace-Rules.md
Hi,
this pull request adds documentation for the workspace rules defined in [Hyprland PR #1986](https://github.com/hyprwm/Hyprland/pull/1986). Hope everything looks ok.
Cheers
=> Added documentation for workspace rules

pages/Plugins/Using-Plugins.md
Companion pr for hyprwm/Hyprland#2180
=> Document declarative plugin config entries (hyprwm/Hyprland#2180)

pages/Configuring/Using-hyprctl.md
=> Add `activeworkspace`

pages/Useful Utilities/Clipboard-Managers.md
https://github.com/hluk/CopyQ/issues/2352
=> add how to make copyq work properly

pages/Configuring/Dispatchers.md, pages/Configuring/Dwindle-Layout.md
Wiki entry for: https://github.com/hyprwm/Hyprland/pull/2240
=> Add preselect to Dwindle

pages/Configuring/Dispatchers.md
See Hyprland PR https://github.com/hyprwm/Hyprland/pull/2198
=> Documentation for "WS on monitor or empty"

pages/Configuring/Dispatchers.md, pages/Nix/Options & Overrides.md
Companion pr for hyprwm/Hyprland#2211
=> Document home manager plugins array

pages/Configuring/Master-Layout.md
this is a companion to PR #2025 on hyprwm/Hyprland
=> added description of new option allow_small_split

pages/Getting Started/Installation.md
found I was missing cmd cpio on my system
=> Add cpio for ArchLinux build dependency

pages/FAQ/_index.md
In my previous pr #229 I accidentally added a dead link lmao
=> Fix dead link

pages/Configuring/Monitors.md
Explicitly say that you can combine extra args for monitor rules
=> Add more details about combining extra args for monitor rule

pages/Nvidia/_index.md, pages/Useful Utilities/App-Launchers.md
=> Added Hyprland Nvidia Patch

pages/Configuring/Dispatchers.md
=> feat: document lockactivegroup dispatcher

pages/Configuring/Binds.md
Companion for hyprwm/Hyprland#2503
=> Add documentation for non-consuming binds

pages/Configuring/Dwindle-Layout.md
This adds some docs for the smart_split option introduced in hyprwm/Hyprland#2676
=> dwindle: document smart_split

pages/Configuring/Variables.md
adds group_insert_after_current
=> group_insert_after_current

pages/Configuring/Dwindle-Layout.md
- documented dwindle:smart_resizing
- fixed table rendering on github
=> document dwindle:smart_resizing

pages/Configuring/Dwindle-Layout.md, pages/Configuring/Master-Layout.md
=> no_gaps_when_only

pages/Configuring/Dispatchers.md
Closes https://github.com/hyprwm/Hyprland/issues/2845
=> dispatchers: dpms: add toggle to state list

pages/FAQ/_index.md
Simplifies the autostarting of apps without the need for cleanup script, discussed in #281
=> Simplify autostarting apps

pages/Useful Utilities/Status-Bars.md
Corrected the waybar style.css path
=> [fix] Corrected file path 

pages/Plugins/Using-Plugins.md
https://github.com/hyprwm/hyprland-plugins/issues/35
=> Add reminder to re-compile plugins after updating Hyprland.

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/2915
=> background: add background color option

pages/Configuring/Dispatchers.md, pages/Configuring/Window-Rules.md
https://github.com/hyprwm/Hyprland/pull/2935
=> respect reserved area in center/centerwindow

pages/Useful Utilities/Hyprland-desktop-portal.md
Sorry for not doing this the first time round.
=> Make the script for disabling imcompatible portals portable

pages/Configuring/Workspace-Rules.md
https://github.com/hyprwm/Hyprland/pull/2956
=> add shadow workspace rule

pages/Configuring/Using-hyprctl.md
was using the description for activewindow
=> fix mistake in hyprctl activeworkspace description

pages/Nvidia/_index.md
I've seen too many(1) people ask "where do I put this"
=> clarify which config to add env var

pages/FAQ/_index.md
=> remove wlroots/3451 issue from FAQ section

pages/Configuring/Animations.md
https://github.com/hyprwm/Hyprland/pull/3008
=> Animations: document slidefade and slidefadevert styles for workspaces

pages/Configuring/Animations.md
slidefade/slidefadevert are for workspaces not windows
=> Animations: fix slidefade example

pages/Configuring/Variables.md
=> feat(debug): add debug:suppress_errors.

pages/Useful Utilities/Wallpapers.md
Adding a GUI tool called Waypaper to the list of wallpaper tools
=> Add waypaper to wallpaper tools

pages/Configuring/Variables.md
for https://github.com/hyprwm/Hyprland/pull/3052
not sure if this is the best way to word it 😅
=> gestures: document workspace_swipe_direction_lock

pages/Configuring/Environment-variables.md, pages/FAQ/_index.md, pages/Getting Started/Master-Tutorial.md, pages/Useful Utilities/Must-have.md
Reference: https://en.wikipedia.org/wiki/Qt_(software)
=> Fix Qt typos

pages/IPC/_index.md
https://github.com/hyprwm/Hyprland/pull/3163
=> add "activespecial"

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/3102
=> add misc:groupbar_scrolling

pages/Useful Utilities/Status-Bars.md
Waybar now supports Hyprland by default with a module.
=> Waybar: update documentation

pages/Useful Utilities/Clipboard-Managers.md
it's wl-clip-persist not wl-clip-persists
=> Fix typo in Clipboard-Managers.md

pages/Configuring/Variables.md
Docs for https://github.com/hyprwm/Hyprland/pull/3189
=> add option scroll_button_lock

pages/Configuring/Master-Layout.md
Wiki update for https://github.com/hyprwm/Hyprland/pull/3210
=> Add smart_resizing for master layout

pages/Configuring/Dispatchers.md
=> resizeparams updates

pages/Configuring/Window-Rules.md
for https://github.com/hyprwm/Hyprland/pull/3247
=> wrv2 move onscreen

pages/Configuring/Master-Layout.md
wiki mr for https://github.com/hyprwm/Hyprland/pull/3298
=> Add master mfact dispatcher

pages/Configuring/Dispatchers.md
my obvious error resulted from four generations of inbreeding.
=> fix movewindoworgroup doc

pages/Configuring/Dispatchers.md
for https://github.com/hyprwm/Hyprland/pull/3217
=> Alterzorder

pages/Configuring/Dispatchers.md, pages/Configuring/Variables.md, pages/Configuring/Window-Rules.md
=> doc window rule `group`

pages/Configuring/Dispatchers.md
Good info for new users in my opinion.
=> Clarify alterzorder

pages/Configuring/Variables.md
Added tablet variables:
- transform
- output
- region_position
- region_size
=> Add tablet variables

pages/Useful Utilities/Screen-Sharing.md
=> fix typo in screen sharing 2

pages/Nvidia/_index.md
Mention the Nouveau driver. In my case, it is far better than nvidia or nvidia-open. No problems at all with it using multiple monitors.
=> Keep the Nouveau driver in mind.

pages/Configuring/Master-Layout.md
wiki pr for https://github.com/hyprwm/Hyprland/pull/3465
=> add master:drop_at_cursor

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/3459
=> added wiki entry for my PR

pages/Configuring/Workspace-Rules.md
This is to document the rule added in https://github.com/hyprwm/Hyprland/pull/3530.
=> Add persistent workspace rule

pages/Configuring/Variables.md
adds `group` and `group:groupbar` sections
https://github.com/hyprwm/Hyprland/pull/3522
=> add group and groupbar sections

pages/Nix/Hyprland on Home Manager.md, pages/Nix/Hyprland on NixOS.md
I found out about this comprehensive and easy solution yesterday and it solved all my problems with themes not loading since switching to wayland/hyprland. I think that this is useful for others and would save them time and hassle trying to fix such a problem.
=> Hyprland on NixOS: add section detailing how to fix problems with themes not working

pages/Contributing and Debugging/_index.md
Minor file extensions mistake.
=> fix incorrect debug build log path

pages/Configuring/Using-hyprctl.md
Connected to PR https://github.com/hyprwm/Hyprland/pull/3630
=> Query workspaces rules

pages/Configuring/Workspace-Rules.md
This PR documents the new `on-created-empty` workspace rule to be added in hyprwm/Hyprland#3559.
- hyprwm/Hyprland#3559
=> Document `on-created-empty` workspace rule

pages/Configuring/Variables.md
Documentation for https://github.com/hyprwm/Hyprland/pull/3751.
=> Document group:groupbar:font_family

pages/Configuring/Variables.md
Docs update for: https://github.com/hyprwm/Hyprland/pull/3650
=> update blur docs

pages/Plugins/Development/Event-list.md
see https://github.com/hyprwm/Hyprland/pull/3836
=> add touch event hooks

pages/Configuring/Monitors.md, pages/Configuring/Using-hyprctl.md
Wiki changes for the changes to hyprctl monitors
https://github.com/hyprwm/Hyprland/pull/3730
=> Updated hyprctl monitor docu to include the all flag

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/3877
=> add animations:workspace_gap

pages/Configuring/Dispatchers.md
Related https://github.com/hyprwm/Hyprland/pull/3923
=> Update execr dispatcher description

pages/Configuring/Variables.md
Related to https://github.com/hyprwm/Hyprland/pull/3933
=> Adding first_launch_animation

pages/Configuring/Window-Rules.md
my motivation for this is [this discussion](https://github.com/hyprwm/Hyprland/discussions/3903)
=> add window rule case sensitivity disclaimer

pages/Configuring/Perfomance.md, pages/FAQ/_index.md, pages/Useful Utilities/Perfomance.md
After finding a solution to this problem I had https://github.com/hyprwm/Hyprland/issues/3959 I thought it would be a good idea to document it so other people know what to do if they stumble upon the same problem. Not only that, I also believe that it would be great to have such category in the hyprland wiki where tricks and known solutions could be documented for people who seek to get more performance out of hyprland.
For now, there is only fix for fractional scaling from the mentioned issue. Though I believe that this page would be very useful when more stuff gets added to it.
Any suggestions or recommendations would be appreciated!
=> Perfomance category suggestion

pages/Configuring/Master-Layout.md, pages/Configuring/Workspace-Rules.md
Wiki MR for https://github.com/hyprwm/Hyprland/pull/3964
=> Add master orientation workspace rule

pages/Plugins/Development/Plugin-Guidelines.md, pages/Plugins/Using-Plugins.md
https://github.com/hyprwm/Hyprland/pull/4072
=> Add hyprpm docs

pages/Configuring/Variables.md
Complements https://github.com/hyprwm/Hyprland/pull/4101.
=> Variables: add scroll_points

pages/FAQ/_index.md
Addresses stuff like https://github.com/hyprwm/Hyprland/issues/2661
=> Add fix for disappearing context menus

pages/Useful Utilities/Must-have.md
Just a quick addition to the list of notification daemons :)
=> Add SwayNotificationCenter to Must-have.md

pages/Configuring/Master-Layout.md
Wiki MR for https://github.com/hyprwm/Hyprland/pull/4209
=> Master layout: add rollnext and rollprev

pages/Configuring/Window-Rules.md
https://github.com/hyprwm/Hyprland/pull/4259
=> Added initialTitle and initialClass to windowrules

pages/Configuring/Window-Rules.md
Accompanies https://github.com/hyprwm/Hyprland/pull/4335
=> Add border gradients

pages/Configuring/Dispatchers.md
Document the dispatcher implemented in https://github.com/hyprwm/Hyprland/pull/4439.
=> document `focusworkspaceoncurrentmonitor` dispatcher

pages/Configuring/Keywords.md, pages/Configuring/Variables.md
cross reference https://github.com/hyprwm/Hyprland/pull/4517
=> Document input:touchdevice:enabled and device:$touchdevice:enabled

pages/Nvidia/_index.md
While slightly tongue-in-cheek in point 3, the advice is the serious result of several evenings' attempts at improving results on my setup.
=> Add further advice to nvidia flickering

pages/Configuring/Monitors.md
Adding this to the wiki, because the solution is really hard to Google right now.
=> Show example of how to rotate touchscreen

pages/Configuring/Dispatchers.md
for https://github.com/hyprwm/Hyprland/pull/3245
=> movewindow (floating)

pages/Useful Utilities/Other.md
=> Add hyprshade to "other" useful utilities

pages/Configuring/Uncommon-tips-&-tricks.md
I had to find this on reddit lol
=> Add info for how to swap caps lock and escape

pages/Useful Utilities/Must-have.md
in connection to [this](https://github.com/hyprwm/Hyprland/issues/4658#issuecomment-1936417289)
=> Fixed info about pipewire and systemd

pages/Useful Utilities/Must-have.md
=> edited markup

pages/Useful Utilities/Must-have.md
=> Reformatted sentences

pages/Configuring/Using-hyprctl.md
for https://github.com/hyprwm/Hyprland/pull/4672
=> add `forcenofocus`

pages/Configuring/Dwindle-Layout.md
See-Also: https://github.com/hyprwm/Hyprland/pull/4702
=> dwindle: document swapsplit

pages/IPC/_index.md
ref https://github.com/hyprwm/Hyprland/pull/4646
=> ipc: document monitoraddedv2

pages/Configuring/Dispatchers.md
Wiki mr for [hyprwm/Hyprland#4720](https://github.com/hyprwm/Hyprland/pull/4720)
=> Add extra option to fullscreen dispatcher

pages/Configuring/Dispatchers.md
Updates the wiki to reflect https://github.com/hyprwm/Hyprland/pull/4724
=> Updated moveoutofgroup params

pages/Useful Utilities/Hypr-Ecosystem.md
=> Fix the URL to XDPH

pages/Crashes and Bugs/_index.md
wiki update for https://github.com/hyprwm/Hyprland/pull/4719
=> Change cache dir

pages/Hypr Ecosystem/hyprlock.md
Placeholder variable uses underscore instead of dash, minor fix.
edit: also first time doing a pull request via web interface, don't know why it adds the second line
=> Fix input field variable name

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/24
=> hyprlock: mention dot's config options

pages/Configuring/Variables.md, pages/Configuring/Workspace-Rules.md
wiki entry for: https://github.com/hyprwm/Hyprland/pull/4723
=> feat: Add documentation about css gaps

pages/Configuring/Keywords.md, pages/Configuring/Uncommon-tips-&-tricks.md, pages/Configuring/Variables.md
This is a companion PR to hyprwm/Hyprland#4851, in which I introduce a new configuration option. This is simply the documentation of its behavior.
=> Document behavior of new resolve_binds_by_sym option

pages/Hypr Ecosystem/hypridle.md
added full hypridle example work with hyprlock for better understanding.
=> add full hypridle example work with hyprlock.

pages/Configuring/Using-hyprctl.md
This documents notification the dismissing feature, implemented in https://github.com/hyprwm/Hyprland/pull/4790
=> Mention notification dimissing

pages/Configuring/Binds.md
This is an accompanying PR to hyprwm/Hyprland#4930, in which I have introduced a new keyword that is documented here.
=> Include new catchall keyword in binds docs

pages/Hypr Ecosystem/hyprlock.md
[hyprwm/hyprlock#127](https://github.com/hyprwm/hyprlock/pull/127)
=> Add rounding option to input field

pages/Configuring/Dwindle-Layout.md
pseudotile value is `bool` not `[0/1/2]`
=> fix error description for pseudotile

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/130
=> hyprlock: mention `dots_rounding`

pages/Hypr Ecosystem/hypridle.md
added how to run hypridle and more details in full example.
=> Added more details for full example.

pages/Configuring/Keywords.md, pages/Configuring/Variables.md
Pairs nicely with PR https://github.com/hyprwm/Hyprland/pull/4980
=> update docs for input:scroll_factor

pages/Configuring/Using-hyprctl.md
Documents https://github.com/hyprwm/Hyprland/pull/4981
=> Mention the ability to set font-size for notifications

pages/Configuring/Binds.md
=> Update docs about bind of switch

pages/Configuring/Using-hyprctl.md, pages/Configuring/Window-Rules.md
For https://github.com/hyprwm/Hyprland/pull/4775
=> convert min/maxsize to dynamic

pages/IPC/_index.md
New events are introduces in https://github.com/hyprwm/Hyprland/pull/5022
=> Add 5 new ipc events

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/154
=> hyprlock: add fail display changes

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/169
=> hyprlock: mention `SIGUSR2`

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/172
=> hyprlock: mention `check_color`

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/182
=> hyprlock: add capslock and numlock options

pages/Configuring/Variables.md
=> Document resize_corner

pages/Hypr Ecosystem/hyprlock.md
Part of https://github.com/hyprwm/hyprlock/pull/188
=> hyprlock: add `no_fade_out` option

pages/Configuring/Master-Layout.md
Was just reviewing options in the wiki and noticed this table was borked.
=> Fix table formatting in Workspace Rules

pages/Configuring/Binds.md, pages/Configuring/Configuring-Hyprland.md, pages/Configuring/Dispatchers.md, pages/Configuring/Environment-variables.md, pages/Configuring/Expanding-functionality.md, pages/Configuring/Keywords.md, pages/Configuring/Monitors.md, pages/Configuring/Uncommon-tips-&-tricks.md, pages/Configuring/Using-hyprctl.md, pages/Configuring/Variables.md, pages/Configuring/Window-Rules.md, pages/Configuring/Workspace-Rules.md, pages/Configuring/XWayland.md, pages/Contributing and Debugging/_index.md, pages/Crashes and Bugs/_index.md, pages/FAQ/_index.md, pages/Getting Started/Installation.md, pages/Getting Started/Master-Tutorial.md, pages/Hypr Ecosystem/hyprcursor.md, pages/Hypr Ecosystem/xdg-desktop-portal-hyprland.md, pages/IPC/_index.md, pages/Nix/Hyprland on NixOS.md, pages/Nix/Hyprland on other distros.md, pages/Nix/Options & Overrides.md, pages/Nix/_index.md, pages/Plugins/Development/Getting-Started.md, pages/Plugins/Using-Plugins.md, pages/Useful Utilities/_index.md, pages/_index.md
Fixes the issue discussed in #458.
=> Convert links back to case-sensitive

pages/Nix/Hyprland on NixOS.md
See issue hyprwm/Hyprland#5148 for more information.
=> Warn people to use the latest mesa version when using the Hyprland flake

pages/Configuring/Variables.md
Reference: https://github.com/hyprwm/Hyprland/pull/4489
=> Gestures: document touchscreen workspace-swipe configuration

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/191
=> hyprlock: add Image widget section

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/201
=> hyprlock: add `swap_font_color` and explanation

pages/Configuring/Variables.md
=> Update tablet variables

pages/Configuring/Using-hyprctl.md
https://github.com/hyprwm/Hyprland/pull/5211
=> Add rollinglog

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/211
=> hyprlock: add `$LAYOUT` for labels

pages/Configuring/Multi-GPU.md
Initial rewrite of multi GPU setup as raised here.
https://github.com/hyprwm/hyprland-wiki/issues/551
=> Rewriting documentation to set WLR_DRM_DEVICES

pages/Useful Utilities/Must-have.md
In Must-have.md corrected 'deciated' to 'dedicated'
=> Fixed typo in Must-have.md

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/234
=> hyprlock: add `rotate` option to label and image

pages/Hypr Ecosystem/hyprlock.md
for https://github.com/hyprwm/hyprlock/pull/248
=> hyprlock: add `$DESC` for labels

pages/FAQ/_index.md
I think it would be better if the wiki uses gender neutral language when addressing the reader to avoid making anyone uncomfortable.
=> Use gender-neutral language when addressing the reader

pages/Configuring/Animations.md
For https://github.com/hyprwm/Hyprland/pull/5421
=> animations: layersIn, layersOut, fadeLayersIn, fadeLayersOut

pages/Hypr Ecosystem/hyprpaper.md
for https://github.com/hyprwm/hyprpaper/pull/160
=> hyprpaper: add splash_color

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/247
=> hyprlock: add reload options to Image

pages/Configuring/Variables.md
hyprwm/Hyprland#4177
Am I allowed to use line-breaks?
=> input:off_window_axis_events values

pages/Configuring/Keywords.md
`I use hyprland-wiki BTW `  but it's better with this humble space
=> add a humble space

pages/Configuring/Using-hyprctl.md
Companion PR for https://github.com/hyprwm/Hyprland/pull/5513.
=> Allow gradient in border colors

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/266
=> hyprlock: add Shape widget

pages/Configuring/Master-Layout.md
Update wiki for https://github.com/hyprwm/Hyprland/pull/4766
=> master: update mfact

pages/Hypr Ecosystem/hyprlock.md
ref. https://github.com/hyprwm/hyprlock/issues/280
=> Fix hide_cursor default value

pages/Hypr Ecosystem/hyprlock.md
ref https://github.com/hyprwm/hyprlock/pull/278
=> hyprlock: add text_align label option

pages/Configuring/Dispatchers.md
To go with https://github.com/hyprwm/Hyprland/pull/5597
=> dispatchers: document new `silent` suffix for `movewindow`

pages/Nvidia/_index.md
Hey vax and other maintainers, hoping this PR finds you well.
This PR is my attempt to clean up and add to the Nvidia page. Currently, there is some vital missing information concerning explicit sync and flickering as a whole. I also aimed to correct parts and make other parts easier to understand.
Please let me know if there is formatting issues, typos, or other things you need clearing up or changing, I'll be happy to get involved.
Edit: I can add a small piece regarding joining the discord server and asking for further support in the #hyprland-nvidia channel. Let me know if that would be a nice addition.
=> NVidia: Partial rewrite, Explicit sync, Addition of missing information

pages/Configuring/Workspace-Rules.md
wiki mr for https://github.com/hyprwm/Hyprland/pull/5640
=> Add fullscreen selector

pages/Crashes and Bugs/_index.md
Shows how to bisect. I may have missed another step in git, not sure
=> Add git bisect tutorial

pages/Configuring/Monitors.md
See: https://github.com/hyprwm/Hyprland/pull/5670
=> Add More Monitor 'Auto' Positions.

pages/Nvidia/_index.md
modified:   pages/Nvidia/_index.md
=> Info callout on WLR_NO_HARDWARE_CURSORS env var for Nvidia since patch

pages/Nvidia/_index.md
Added 'is' to the sentence (#611)
=> Fix a small grammar mistake

pages/Configuring/Binds.md
address https://github.com/hyprwm/Hyprland/issues/5727
=> Suggest to also bind keyboard keys instead of mouse clicks for Touchpads

pages/Configuring/Window-Rules.md
Update wiki for hyprwm/Hyprland#5770
=> update docs for hyprwm/Hyprland#5770

pages/Configuring/Uncommon-tips-&-tricks.md
=> add Minimize windows tip 

pages/Configuring/Variables.md
the docs for hyprwm/hyprland#5847
=> add default_cursor_monitor option

pages/Configuring/Dispatchers.md
not sure about how I wrote this, if have suggestions...
=> Match changes in Hyprland/#5848

pages/Hypr Ecosystem/hyprlock.md
ref. https://github.com/hyprwm/hyprlock/issues/284 (can be closed) and https://github.com/hyprwm/hyprlock/pull/310
=> Add hyprlock text_trim option

pages/Contributing and Debugging/_index.md
I noticed some missing info as a newcomer to the project, I figured i would document it here for future newcomers (:
=> Add LSP, Formatting, and Debugging info.

pages/IPC/_index.md
Replace `/tmp` with *${XDG_RUNTIME_DIR}*
=> Update IPC socket file location

pages/Configuring/Variables.md
=> Actual default value for hide_on_key_press

pages/Configuring/Using-hyprctl.md
Add `locked` command to hyprctl
=> Add locked command

pages/Configuring/Binds.md
Documentation for https://github.com/hyprwm/Hyprland/pull/5966
=> Allow Multiple Simultaneous keys in a Keybind and add Left and Right mod distinction.

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/6111
=> add debug:error_position

pages/Hypr Ecosystem/hyprlock.md
https://github.com/hyprwm/hyprlock/pull/334
=> hyprlock: add zindex

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/6182
=> add window_direction_monitor_fallback

pages/Hypr Ecosystem/hyprpaper.md
Add the description of new keyword (reload) in hyprpaper according to pull request: https://github.com/hyprwm/hyprpaper/pull/173
=> Add the description of new keyword (reload) in hyprpaper

pages/Configuring/Dispatchers.md, pages/Configuring/Window-Rules.md
For this PR: https://github.com/hyprwm/Hyprland/pull/6211
=> dispatcher: add window tag desc

pages/FAQ/_index.md
add an entry in the FAQ about phantom monitor and a potential workaround
=> faq: added an entry about phantom monitor

pages/Nvidia/_index.md
Related: hyprwm/Hyprland#6290
Might save some people a bit of debugging
=> Add a note regarding `egl-wayland` to Nvidia docs

pages/Configuring/Using-hyprctl.md
For https://github.com/hyprwm/Hyprland/pull/6319
=> Add output name setting info

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/6338
=> add cursor:persisten_warps

pages/Configuring/Variables.md
See https://github.com/hyprwm/Hyprland/pull/6342
=> Add gestures:workspace_swipe_min_fingers option

pages/Configuring/Master-Layout.md
https://github.com/hyprwm/Hyprland/pull/6479
=> layout: refine master layout new window handling

pages/Crashes and Bugs/_index.md
Remove install (ref. https://github.com/hyprwm/hyprland-wiki/issues/638)
Add `git bisect skip`
=> Update bisect guide

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/6480
=> add cursor:warp_on_change_workspace

pages/Configuring/Master-Layout.md
Typo I think (backticks missing)
=> Master-Layout: fix typo

pages/Configuring/Dwindle-Layout.md
This PR updates the wiki page for the pseudo dispatcher to reflect the new argument added by #6583 in the main Hyprland project.
=> Update pseudo dispatcher to feature the new argument

pages/Configuring/Performance.md
https://wiki.hyprland.org/Configuring/Variables/#blur
decoration:blur = false does not work in configuration file
=> performance: add enabled property to decoration:blur

pages/Nvidia/_index.md
- Adds information about 555 drivers
- Remove `xorg-xwayland-git` installation
- Grammar fixes
=> Update Nvidia page

pages/Useful Utilities/App-Launchers.md
the repo moved, this commit updates the link
=> update anyrun github link

pages/Configuring/Dispatchers.md
https://github.com/hyprwm/Hyprland/pull/6598
=> feat: previous workspace per monitor

pages/Useful Utilities/Clipboard-Managers.md
[clipse](https://github.com/savedra1/clipse) has been gaining popularity amongst the Hyprland community lately, so thought I'd get it up on here as an option. Please let me know if you have any concerns/questions. Thanks!
=> docs: add 'clipse' to Cipboard-Managers.md

pages/Hypr Ecosystem/hyprlock.md
=> hyprlock: add general:immediate_render option

pages/FAQ/_index.md
The command here is wrong and not consistent to the one on Performance page: https://wiki.hyprland.org/Configuring/Performance/
=> Correct blur disable keyword

pages/IPC/_index.md
Add windowtitlev2 to match added event in PR for Hyprland
=> Add windowtitlev2 to match added event in PR #6856 for Hyprland

pages/Configuring/Variables.md
Wiki documentation for
```
misc { 
exit_window_retains_fullscreen = true
}
```
Implementation pull request (Hyprland):
- https://github.com/hyprwm/Hyprland/pull/6880
=> docs: added variable misc:exit_window_retains_fullscreen

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/6881
=> Document input:emulate_discrete_scroll variable

pages/Configuring/Environment-variables.md, pages/Configuring/Multi-GPU.md, pages/Configuring/Tearing.md, pages/Configuring/Variables.md, pages/Crashes and Bugs/_index.md, pages/FAQ/_index.md, pages/Getting Started/Installation.md, pages/Nvidia/_index.md
ref https://github.com/hyprwm/Hyprland/pull/6608
=> Aquamarine stuff

pages/Configuring/Variables.md
I have error that there isn't such a variable. Well, I thought it's removed from the codebase.
=> Removed the suppress_portal_warnings variable, since it's not in the codebase.

pages/Getting Started/Installation.md
Simply add Debian as there is a package in the SID repos which I am daily driving is working great
=> Add Debian to installation.md

pages/Hypr Ecosystem/hyprlock.md
ref: https://github.com/hyprwm/hyprlock/pull/456
=> hyprlock: add fractional_scaling option

pages/Getting Started/Installation.md
Just sharing what I find useful.
The Chaotic Aur is awesome and downgrade makes it quick and easy to, well, downgrade, especially with the Chaotic Aur.
=> Installation: Add Chaotic AUR and `downgrade` mention

pages/Configuring/Master-Layout.md
The description for mfact was incorrect, it was copy-pasted from the dispatcher below. I fixed it to be clearer and correct.
=> [PR] Fixed the description of the mfact variable in the Master Layout page.

pages/Configuring/Variables.md, pages/Nvidia/_index.md
ref https://github.com/hyprwm/Hyprland/pull/7151
=> Explicit sync wiki changes

pages/Getting Started/Installation.md
Updates to tell users about hyprland in the trixie repos and add Ubuntu
=> Change the Debian section and add unbuntu

pages/Configuring/Window-Rules.md
adds fullscreenstate windowrule
=> add fullscreenstate windowrule

pages/Configuring/Variables.md
add a section to cursors about sync_gsettings_theme
https://github.com/hyprwm/Hyprland/pull/7253
=> Document sync_gsettings_theme in cursor

pages/Configuring/Variables.md
I also formatted the entire file because it was barely readable. If not wanted I can remove the commit.
=> Specify that new_window_takes_over_fullscreen applies also to maximized windows

pages/Configuring/Environment-variables.md
=> Document HYPRLAND_NO_SD_VARS

pages/Configuring/Variables.md
Document for [Hyprland/pull/7368](https://github.com/hyprwm/Hyprland/pull/7368)
=> docs: docs for Hyprland/pull/7368 (focus_on_close)

pages/Configuring/Window-Rules.md
Wiki for `fullscreenstate` window rules v2 field.
For main repo MR: https://github.com/hyprwm/Hyprland/pull/7466
=> docs: add fullscreenstate window rules v2 field

pages/Configuring/Window-Rules.md
Changed the window rules v2 fields' code block to a table.
=> refactor: use table for window rules v2 field

pages/Nix/Hyprland on Home Manager.md
=> Fix nix loop for workspaces #514

pages/Configuring/Variables.md
docs PR for https://github.com/hyprwm/Hyprland/pull/7633
=> docs: add xwayland:enabled

pages/Configuring/Variables.md
Relevant Hyprland PR: [Hyprland/pull/7368](https://github.com/hyprwm/Hyprland/pull/7650)
=> docs: added config entry for `group:merge_groups_on_drag`

pages/Crashes and Bugs/_index.md
...also fix a minor capitalization error that bugged me...
=> wiki: simplify stacktrace instructions and add outputting to file

pages/Configuring/Keywords.md
wiki PR for https://github.com/hyprwm/Hyprland/pull/7683
=> wiki: add exec-shutdown

pages/Configuring/Window-Rules.md
Documents hyprwm/hyprland#7697
=> Configuring/Window Rules: document new order layerrule

pages/Configuring/Environment-variables.md, pages/FAQ/_index.md
=> Document AQ envs, and some more for AQ_NO_MODIFIERS

pages/Configuring/Variables.md
See Hyprland/src/config/ConfigManager.cpp
=> Fixed default value of input:touchpad:tap-and-drag

pages/Configuring/Environment-variables.md
Reflecting a change that was made in the main branch of Hyprland.
=> chore: add HYPRLAND_CONFIG to the "Environment variables" page

pages/Getting Started/Installation.md
Packages of the Hyprland ecosystem are available in Ximper Linux.
It is planned to create a separate build based on this window manager in the near future.
=> Add install instructions for Ximper Linux

pages/Configuring/Dwindle-Layout.md
Document for https://github.com/hyprwm/Hyprland/pull/7903.
=> add document for `movetoroot` layout message

pages/Hypr Ecosystem/xdg-desktop-portal-hyprland.md
=> Fixed bad link

pages/Useful Utilities/Status-Bars.md
when using hyprland instead of sway also replace mode with submap
=> Waybar with hyprland requires submap

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/7883
=> auto_group

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/8004
=> drag_into_group

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/8042
=> merge_floated_into_tiled_on_groupbar

pages/Hypr Ecosystem/hyprlock.md
Ref: https://github.com/hyprwm/hyprlock/pull/508
=> hyprlock: add dots_fade_time option

pages/Hypr Ecosystem/hyprlock.md
Ref: https://github.com/hyprwm/hyprlock/pull/510
=> hyprlock: add input-field:dots_text_format and related changes

pages/Configuring/Variables.md, pages/Configuring/Window-Rules.md
=> clarify disabling auto group only for specific windows

pages/Configuring/Animations.md
Per discussion https://github.com/hyprwm/Hyprland/issues/7711#issuecomment-2409083703
=> Update to include warning about using borderangle style loop

pages/Plugins/Using-Plugins.md
In relation to https://github.com/hyprwm/Hyprland/pull/8167
=> hyprpm: Added `-nn` option usage

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/8159
=> add group_on_movetoworkspace

pages/Hypr Ecosystem/hyprsunset.md
=> Fix typo in hyprsunset.md

pages/Useful Utilities/File-Managers.md, pages/Useful Utilities/Other.md, pages/Useful Utilities/_index.md
- add File-Managers.md with weight 10 to Useful Utilities
- update Other.md weight from 10 to 11
- insert link to File-Managers in the _index.md
- fix punctuation of first commit
=> Add File-Managers to Useful Utilities

pages/Configuring/Window-Rules.md
This his related to https://github.com/hyprwm/Hyprland/issues/8277 and hopefully addresses some confusion I (and others had) around the static rules.
=> adding clarifying language for static windowrules

pages/Configuring/Variables.md
Wiki description for https://github.com/hyprwm/Hyprland/pull/8289
=> add snap:border_overlap description

pages/Configuring/Variables.md
=> Resolve #838  "Configuring/Variables xray Description Error"

pages/Hypr Ecosystem/hypridle.md, pages/Hypr Ecosystem/hyprpaper.md, pages/Hypr Ecosystem/hyprpolkitagent.md
Wording may not be the best, but I think it's worth to mention systemd services, as an alternative to exec-once=. Anyway, suggestions are welcome.
=> Add mention about possibility to start hypridle, hyprpaper and hyprpolkit with system services.

pages/Hypr Ecosystem/hyprlock.md
Ref.: https://github.com/hyprwm/hyprlock/pull/541
=> hyprlock: explain ability to use pixels or percentages for position and size

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/8362
=> add merge_groups_on_groupbar

pages/Useful Utilities/Status-Bars.md
Remove unnecessary word 'lets'
=> Fix grammar in Status-Bars.md

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/8352
=> tablet: add absolute_region_position and improve descriptions

pages/Configuring/Variables.md, pages/FAQ/_index.md
https://github.com/hyprwm/Hyprland/pull/8418
=> Updated wiki to match the pull request for changing the default decoration:blur:ignore_opacity value

pages/FAQ/_index.md
I accidentally wrote `Hprwinwrap` instead of `Hyprwinwrap` and managed to completely miss it.
Not sure if another pr was needed, let me know if I should go about it some other way.
=> Fixed a typo I made in FAQ

pages/Useful Utilities/Systemd-start.md
fix redirect links in Systemd-start.md
=> fix redirect links in Systemd-start.md

pages/Configuring/Dispatchers.md, pages/Configuring/Environment-variables.md, pages/Hypr Ecosystem/hypridle.md, pages/Hypr Ecosystem/hyprpaper.md, pages/Hypr Ecosystem/hyprpolkitagent.md, pages/Useful Utilities/Status-Bars.md
These should be the last ones I missed
=> Fix  the remaining links to UWSM

pages/Useful Utilities/App-Clients.md
It is very popular, and by far the best screensharing experience i found so far.
=> Describe vesktop client for Discord

pages/Useful Utilities/Systemd-start.md
https://github.com/hyprwm/Hyprland/discussions/8459#discussioncomment-11248704
=> Code-tag "Hyprland"

pages/Configuring/Binds.md
for https://github.com/hyprwm/Hyprland/pull/8302
=> bind: new long press option

pages/Configuring/Variables.md
Added documentation related to lockdead_screen_delay
=> Add lockdead_screen_delay description

pages/Configuring/Environment-variables.md
=> Environment-variables - add information - how to export variables, using UWSM

pages/Plugins/Development/Event-list.md
this PR complements Hyprland's https://github.com/hyprwm/Hyprland/pull/8503
=> Add new monitor added/removed events

pages/Useful Utilities/Status-Bars.md
blurls no longer exist in hyprland afaik, use layer rules.
=> change blurls to layer rules

pages/Configuring/Variables.md
For https://github.com/hyprwm/Hyprland/pull/8521
=> variables: add input_methods and input_methods_ignorealpha

pages/Configuring/Variables.md
for https://github.com/hyprwm/Hyprland/pull/8526
=> add: binds:allow_pin_fullscreen

pages/Useful Utilities/Systemd-start.md
https://github.com/hyprwm/hyprland-wiki/pull/874#issuecomment-2495140340
=> Systemd-Start - update the link to Environment-Variables page

pages/Getting Started/Installation.md
Add `yay -S  hyprland-meta-git` option to install the whole hypr* ecosystem, at once.
https://aur.archlinux.org/packages/hyprland-meta-git
=> Installation: add a mention of hyprland-meta package under Arch section

pages/Configuring/Variables.md
=> variables: update `cursor:warp_on_change_workspace` description

pages/Configuring/Variables.md
Relevant PR: https://github.com/hyprwm/Hyprland/pull/8601
=> Docs for 'Modified the movefocus dispatcher to prioritize focus change within groups. #8601'

pages/Hypr Ecosystem/hyprlock.md
ref.: https://github.com/hyprwm/hyprlock/pull/578
=> hyprlock: move auth related options

pages/Plugins/Development/Getting-Started.md
As it was renamed in https://github.com/hyprwm/Hyprland/pull/8635
=> docs: rename `CColor` to `CHyprColor`

pages/Hypr Ecosystem/hyprlock.md
Not related to any hyprlock pr. Just an improvement.
=> hyprlock: improve doc for the `monitor` option

pages/Hypr Ecosystem/hyprlock.md
Variable added in https://github.com/hyprwm/hyprlock/pull/613
=> Hypr Ecosystem/hyprlock.md: Add documentation for $FPRINTPROMPT

pages/Hypr Ecosystem/hyprlock.md
ref. https://github.com/hyprwm/hyprlock/issues/616 and https://github.com/hyprwm/hyprlock/pull/627
=> hyprlock: add timezone documentation

pages/IPC/_index.md
ref. https://github.com/hyprwm/Hyprland/pull/8921
=> ipc: add focusedmonv2

pages/Configuring/Master-Layout.md
This change is for when https://github.com/hyprwm/Hyprland/pull/8926 is merged.
=> layouts: add loop option to master layout cycle commands

pages/Configuring/Master-Layout.md
Related to [#8940](https://github.com/hyprwm/Hyprland/pull/8940)
=> Configuring/Master-Layout.md: add option to  show slaves on left in master center orientation

pages/Configuring/Variables.md
=> HDR: Update Variables.md

pages/Configuring/Dispatchers.md
ref https://github.com/hyprwm/Hyprland/pull/8962
=> dispatchers: add forcekillactive, killwindow, signal, signalwindow

pages/Configuring/Window-Rules.md
ref https://github.com/hyprwm/Hyprland/pull/8965
=> Window-Rules: add new ```suppressevent``` for ```fullscreenoutput```

pages/Configuring/Keywords.md
ref: https://github.com/hyprwm/Hyprland/pull/8953
=> keyword: exec-once

pages/Hypr Ecosystem/hyprlock.md
Ref.: https://github.com/hyprwm/hyprlock/pull/641
=> hyprlock: add/remove vars and add a dedicated section about variable-substitution

pages/Getting Started/Installation.md
Ref: https://github.com/hyprwm/Hyprland/pull/9106
=> Getting Started/Installation: add NO_HYPRPM info, Meson custom flags

pages/Hypr Ecosystem/hypridle.md
Ref.: https://github.com/hyprwm/hypridle/pull/122
=> hypridle: add general on_(un)locked_cmd and inhibit_sleep

pages/Configuring/Keywords.md
=> Configuring/Keywords: fix broken links

pages/Useful Utilities/Systemd-start.md
uwsm is now in official Arch repo.
=> Systemd Start: Update Arch installation instructions

pages/Configuring/Variables.md, pages/Configuring/Window-Rules.md
https://github.com/hyprwm/Hyprland/pull/9226
=> Content type changes

pages/Configuring/Dispatchers.md
https://github.com/hyprwm/Hyprland/pull/5548
=> dispatchers: add toggleswallow

pages/Configuring/Workspace-Rules.md
Related PR: [Hyprland#9344](https://github.com/hyprwm/Hyprland/pull/9344)
=> Hyprland#9344 - workspace rules - pinned window flag

pages/Getting Started/Installation.md
=> Update Fedora version numbering from 39 to 40 (as Fedora 39 is EOL now)

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/9373
https://github.com/hyprwm/Hyprland/commit/9c38287410b305503f921e411eb39686b23ccc42
default value is false
=> group:groupbar:gradients

pages/Hypr Ecosystem/hyprsunset.md
For https://github.com/hyprwm/hyprsunset/pull/18
=> hyprsunset: Add IPC support

pages/Configuring/Variables.md
added entry for the variable introduced by hyprwm/Hyprland#9392
=> variables: added follow_mouse_threshold

pages/Useful Utilities/Clipboard-Managers.md
Users may be interested to this
=> Useful Utilities/Clipboard Managers: add stayfocused rule to clipse

pages/Hypr Ecosystem/hyprpicker.md
Updating hyprpicker documentation to match the latest version which is 0.4.2
=> Update hyprpicker.md to match latest version(v0.4.2)

pages/Getting Started/Preconfigured-setups.md
prasanthrangan has changed repos for their dotfiles, and has deprecated the repo that is currently linked in this page. Changing here so it's one less click for users and to avoid confusion
=> Change link and title for prasanthrangan's dotfiles

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/9481
=> docs(input): add flip_x and flip_y for touchpad

pages/IPC/_index.md
Documentation for https://github.com/hyprwm/Hyprland/pull/9530
=> feat(ipc): add activespecialv2

pages/Configuring/Master-Layout.md
https://github.com/hyprwm/Hyprland/pull/9537
=> docs(master): add option to keep master window position

pages/Configuring/Window-Rules.md
https://github.com/hyprwm/Hyprland/pull/9422
=> docs(windowrules): add persistentsize rule

pages/Getting Started/Installation.md
- Add `libre2-dev` source dep
- Use `apt` instead of the old and I think deprecated `apt-get`
=> Update Installation.md - add libre2-dev source dep

pages/Configuring/Variables.md
Related to https://github.com/hyprwm/Hyprland/pull/9553
=> update `transform` default values

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/9578
=> Document groupbar gap vars

pages/Configuring/Monitors.md, pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/9506
=> Simple cm settings

pages/Configuring/Dispatchers.md
https://github.com/hyprwm/Hyprland/pull/9599
=> dispatchers: add sendkeystate

pages/Hypr Ecosystem/hyprlock.md
ref. https://github.com/hyprwm/hyprlock/pull/714
=> Hypr Ecosystem/hyprlock: remove disable_loading_bar option

pages/Configuring/Variables.md
Adds description of new config value introduced by https://github.com/hyprwm/Hyprland/pull/9728
=> Configuring/Variables: add binds:hide_special_on_workspace_change

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/9782
=> variables: add anr_missed_pings 

pages/Hypr Ecosystem/hyprlock.md
Ref: https://github.com/hyprwm/hyprlock/pull/718
=> hyprlock: move fail_timout from input-field to general

pages/Hypr Ecosystem/hyprlock.md
Ref: https://github.com/hyprwm/hyprlock/pull/727
=> hyprlock: add input-field:hide_input_base_color

pages/Configuring/Window-Rules.md
=> windowrules: missed some windowrule-v1 examples -> update to class: syntax

pages/Configuring/Dispatchers.md
adds examples for https://github.com/hyprwm/Hyprland/pull/9566
=> add setprop relative examples

pages/Configuring/Keywords.md
https://github.com/hyprwm/Hyprland/pull/10064
=> Keywords: document `keybinds` regarding devices

pages/Configuring/Window-Rules.md
https://github.com/hyprwm/Hyprland/pull/9994
=> windowrules: document nofollowmouse

pages/Hypr Ecosystem/hyprpaper.md
Also formatted the markdown with Prettier, but the hyprpaper change was the only one of substance.
=> Hypr Ecosystem/hyprpaper: added example random wallpaper script for multi-monitor setups

pages/Configuring/Multi-GPU.md
extra " ' " was added at the last ,at line : 19
=> Update Multi-GPU.md, corrected a command

pages/Configuring/_index.md
=> configuring: correct start page link

pages/Configuring/Master-Layout.md
Related to Hyprland pull [#10201](https://github.com/hyprwm/Hyprland/pull/10201)
=> Change center_master_slaves_on_right to center_master_fallback

pages/Useful Utilities/File-Managers.md
Added the awesome lf terminal file manager to File-Managers.md which has a more modern look and implementation than ranger.
=> Added lf to File-Managers.md

pages/Configuring/Uncommon-tips-&-tricks.md
Hello!  I moved to Hyprland and Wayland a few days ago, really appreciate your work on this, I like it a lot.
I hope you would accept this PR, please, let me know if there is anything I should change
Related to hyprwm/Hyprland#9257 and hyprwm/Hyprland#9319
=> Configuring/Uncommon tips&tricks: add mouse reset time callout for zoom trick

pages/IPC/_index.md
documentation for https://github.com/hyprwm/Hyprland/pull/10229
=> IPC: add monitorremovedv2

pages/Configuring/Variables.md
Documents [#10277](https://github.com/hyprwm/Hyprland/pull/10277).
Feel free to change the setting description if anyone thinks they have a better explanation.
=> Add documentation for animations:workspace_wraparound

pages/Hypr Ecosystem/hyprsunset.md
it's available in official repos (https://archlinux.org/packages/extra/x86_64/hyprsunset/)
=> hyprsunset: replace yay with pacman

pages/Configuring/Dwindle-Layout.md
https://github.com/hyprwm/Hyprland/pull/9704
=> fix drag n drop window

pages/Configuring/Monitors.md
https://github.com/hyprwm/Hyprland/pull/10528
=> Configuring/Monitors: add maxwidth resolution mode

pages/Configuring/Uncommon-tips-&-tricks.md
should be the last update everything is smooth and no bug
=> alttab : add alt shift tab for everything.

pages/Useful Utilities/Status-Bars.md
I think these two are worth mentioning for their excellent Hyprland support compared to EWW
For objectiveness I kept their descriptions to a minimum, but please let me know if there is something worth adding.
=> Status bars: add AGS and Quickshell

pages/Configuring/Uncommon-tips-&-tricks.md
Fixes https://github.com/hyprwm/Hyprland/discussions/10607
strange bug
=> alttab again

pages/Hypr Ecosystem/hypridle.md
Add general ignore_wayland_inhibit option to table
=> hypridle.md: add general ignore_wayland_inhibit option to table

pages/Hypr Ecosystem/hypridle.md
The table includes the new per-listener ignore_inhibit option, added in PR https://github.com/hyprwm/hypridle/pull/158
Additionally, add an Examples heading (h3) above the full example.
[ reissuing this PR on top of my previous edit PR for this page ]
=> hypridle.md: add listener variables table w/ ignore_inhibit

pages/Configuring/Variables.md
=> variables: add input:touchpad:drag_3fg

pages/Configuring/Dwindle-Layout.md
This documentation change maps to [PR10650](https://github.com/hyprwm/Hyprland/pull/10650) in the main hyperland repo.
=> Add documentation for dwindle:single_window_aspect_ratio and dwindle:single_window_aspect_ratio_tolerance

pages/Configuring/Variables.md
wiki pr for https://github.com/hyprwm/Hyprland/pull/10702.
=> document sticky option for drag_lock

pages/Configuring/Variables.md
=> Configuring/Variables: Add new groupbar color variables

pages/Hypr Ecosystem/hyprlock.md
Ref: https://github.com/hyprwm/hyprlock/pull/802
=> hyprlock: remove grace config option

pages/Hypr Ecosystem/hyprsunset.md
Changed "percieved" to "perceived". Only 2 words.
=> Hypr Ecosystem/hyprsunset.md: Fix typo

pages/Configuring/Environment-variables.md, pages/Nvidia/_index.md
add some info about AQ_FORCE_LINEAR_BLIT
AQ PR: https://github.com/hyprwm/aquamarine/pull/174
=> environment variables: document AQ_FORCE_LINEAR_BLIT

pages/Configuring/Variables.md
remove them, both broken. and unusued
=> remove render ahead of time variables

pages/Configuring/Variables.md
https://github.com/hyprwm/Hyprland/pull/11026
=> Update Variables.md: mpv with cm_auto_hdr

pages/Configuring/Variables.md
Update variables for this pr on hyprland https://github.com/hyprwm/Hyprland/pull/11058
=> Add cursor:invisible

pages/Hypr Ecosystem/hyprsunset.md
really sorry about that, was trying to fix the previous error in a rush and must've overtlooked that
=> add quotation

content/Configuring/Dwindle-Layout.md
Improved split_width_multiplier description, to include widescreen use case.
=> Improved split_width_multiplier description to describe use case.

content/Configuring/Multi-GPU.md
Mentions a solution for the issue of `/dev/dri/card*` paths changing periodically which GPU they point to using a udev rule, which also retains the ability to specify multiple cards in `AQ_DRM_DEVICES`.
=> Add section about udev rule for consitent DRM card device paths

content/Configuring/Dwindle-Layout.md
Coincides with https://github.com/hyprwm/Hyprland/pull/11448
=> Configuring/Dwindle-Layout: update description for `split_bias`

content/Configuring/Window-Rules.md
https://github.com/hyprwm/Hyprland/pull/11370
=> Configuring/Window-Rules: add novrr

content/Configuring/Dwindle-Layout.md, content/Configuring/Environment-variables.md, content/Configuring/Example-configurations.md, content/Configuring/Expanding-functionality.md, content/Configuring/Gestures.md, content/Configuring/Master-Layout.md, content/Configuring/Multi-GPU.md, content/Configuring/Performance.md, content/Configuring/Permissions.md, content/Configuring/Tearing.md, content/Configuring/Uncommon-tips-&-tricks.md, content/Configuring/Using-hyprctl.md, content/Configuring/Variables.md, content/Configuring/XWayland.md
wiki MR for https://github.com/hyprwm/Hyprland/pull/11490
=> gestures: add page

content/Configuring/Animations.md
wiki MR for hyprwm/Hyprland#11574
=> animations: movement param for slide/slidevert

content/Configuring/Binds.md
partial fix for: https://github.com/hyprwm/Hyprland/discussions/11583
=> docs(binds): warning about Systemd HandleLidSwitch conflicts

content/Getting Started/Preconfigured-setups.md
HyDE is actually maintained by HyDE Project, but was inspired by someone's dotfile.
=> Changed HyDE maintainer to HyDE Project

content/Configuring/Window-Rules.md
Added to match [PR #11689](https://github.com/hyprwm/Hyprland/pull/11689)
=> Updated window rule examples and unset.

content/Configuring/Dispatchers.md
=> Updated Dispatchers.md
